### ISSUE TITLE
Usage with Ruby

### ISSUE THREAD

**Issue by BenMorganIO** [dCache/dcache#1305]
Hey there,

I'm looking to give dCache a try and see how it compares against Riak and Redis for a rails application. I wasn't able to find a ruby wrapper on Github.

I was able to find a [gem called dCache](https://github.com/DirtYiCE/DCache), but it doesn't link back to this repository, nor does it explicitly state that its a ruby client for dCache. Its also quite old.

**Comment by paulmillar** [comment]
Hi Ben,

You may be comparing apples with oranges here, especially if you want something like a dedicated key-value store.

dCache is a distributed filesystem with out-of-the-box support for various protocols (NFS v4.1 with pNFS, FTP, WebDAV), different authentication schemes (X.509, Kerberos, username+pw), pluggable user-identity mapping and (if you want it) pluggable integration to tertiary storage (tape systems, cloud back-ends, ...).  What you get is an immutable filesystem (no read-modify-write; but file contents can be atomically replaced) POSIX-like filesystem with consistent access from different protocols.  It's mostly used in laboratories throughout the world to store large amounts of scientific data (~20 PiB is the largest instance that we know of) so that large batch farms have fast and efficient access to that data for scientific analysis work.

As you guessed, it looks like the gem doesn't have anything to do with the dCache project here.

HTH,

Paul.

**Comment by BenMorganIO** [comment]
Its the fact that it can store large amounts of data that I wanted to try it out.

Thanks for getting back to me and letting me know it wouldn't be the best tool for a ruby job.
