### ISSUE TITLE
dcache.org does not redirect to www.dcache.org

### ISSUE THREAD

**Issue by BenMorganIO** [dCache/dcache#1306]
When visiting http://dcache.org I receive no response. Maybe there should be a 301 redirect?

**Comment by calestyo** [comment]
plus the X.509 cert is only valid for "dcache.org".

**Comment by gbehrmann** [comment]
Indeed. @chrber, can you please fix this? Both the cert and the redirect.

**Comment by onnozweers** [comment]
Software should always be downloaded over a secure channel, never over plain HTTP (or FTP), because of MitM risk, but also to not disclose which software I'm downloading with the risk of leaking a potential security vulnerability.
So I'd like to request that the HTTP site does a redirect to the HTTPS site, and that Strict Transport Security (HSTS) is enabled.
I'd like to recommend also to test the site with https://www.ssllabs.com/ssltest/analyze.html?d=dcache.org.

**Comment by onnozweers** [comment]
Some elements (app, img) are directly linked to the HTTP site, so even when browsing to the HTTPS some traffic is unprotected.

**Comment by chrber** [comment]
Website is now as secure as I can make it, redirecting to https at all times. Please provide feedback should I have missed something.

Thanks.
Christian

**Comment by calestyo** [comment]
Cert and dns seems okay,.. but the HTML code would still contain absolute URLs (typically http://).

From a security POV that would still open an attack vector, as the general redirect that you've set up from the plain vhost to the TLS vhost is nothing that can be secured (at least not without HTST, which in turn is nothing I would particularly put much security trust upon).

**Comment by calestyo** [comment]
As for securely downloading packages, the best thing would be if dCache.org would provide (signed) repos, i.e. a "secure APT" repo and... whatever RHEL does (YUM style repos?).

I remember we had some chat about the former in a ticket (#8314) that I've opened a while ago with no real outcome.
In the meantime I've added the dcache.org .debs to my own APT repo, but that's nothing which would work for others, especially as I don't add new packages in time when you release them.

However, running such repo is actually quite simple and I'll provide some info at the aforementioned ticket.

**Comment by gbehrmann** [comment]
If we wanted to put our packages into a repo, we should probably give each release series its own package name, e.g. dcache-2.10 and dcache-2.13. We don't want to have automatic updates from one feature release to the other. This is however quite common, e.g. postgresql is packaged that way (even with support for running multiple versions at the same time, but we don't need that in the first iteration).

**Comment by calestyo** [comment]
Sounds also good,... a meta package could pull in any-of the currently available actual packages (which is a bit different to Debian's postgresql meta package which pulls in the most recent version - but the difference here is that multiple versions of postgresql can co-exist in Debian).

Once you're dcache-2.10 would no longer be supported, it can be moved to e.g. some "archived" suite... making it obsolete in any other suites, so that apt shows the admin, that he needs to act.

**Comment by onnozweers** [comment]
Hi Christian,

Nice job on the HTTPS! An A-rating at Qualys SSL test, that's very good.

Thanks!
Onno
