### ISSUE TITLE
hsm interface need a possibility to skip logging of some error codes

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#1709]
Some HSM systems use the fact that pool will retry flushing to tape and return non zero error as long as backed tape migration not ready. As any failed attempt to flush files get logged in billing, billing files get filled up with such error messages, which are 'OK'.

An option to HSM interface to skip  logging of some error codes will decrease amount of the data send to billing.

**Comment by gbehrmann** [comment]
Alternatively, the script driver could be altered to do this internally. That would seem slightly cleaner to me: What you describe is an altered semantics of the script callout in which rather than blocking until flushed, it polls for the flush to finish. Such semantics ought to be part of the driver itself.

**Comment by paulmillar** [comment]
Return code 72 is recognised as a special exit core requesting that the script is invoked again later.  The polling frequency is controllable via -p:delay option.

This is available since dCache v3.0
