### ISSUE TITLE
bring back update link groups -blocking

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#1771]
Hi.

AFIAU, the -blocking option was dropped from update link groups.
This is kinda bad, cause when doing scripting one may want the results of an e.g. following ls link groups to be current, and when it doesn't block, this may not be the case, right?

Could the option come back?

Cheers,
Chris.

**Comment by paulmillar** [comment]
The `update link groups` command doesn't return until the update has completed; i.e., the `-blocking` option is no longer needed.

Since the command *also* doesn't block any concurrent activity in spacemanager (activity that happens after the update will use the updated information), it is safe to make this the only behaviour for this command, which is why the option was dropped.

**Comment by calestyo** [comment]
Ah thanks... that wasn't clear to me :)
