### ISSUE TITLE
If HSM script restore fails but it exits with 0, dCache checksumming disables pool

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#1807]
If an HSM script fails to restore a file but by mistake exits with a 0, dCache can't open the file to calculate its checksum and throws an IO exception. This disables the entire pool (probably since 2.10.35 - we haven't noticed this before). I think that this specific situation is not a pool issue but should be treated as a problem with a single file; so it seems a bit overkill to disable the entire pool.

We've fixed our HSM script; it does an exit 1 when the restored file is absent. But it would be nice if dCache could handle this a bit more robustly. Therefore this enhancement request.

Thanks!
Onno

**Comment by paulmillar** [comment]
Having talked with Gerd, we've agreed to reject the request.  Here's why:

The pool's current behaviour is the believe the script: it is the script's responsibility to return SUCCESS if and only if the file was successfully restored.  The problem you describe was due to the script returning SUCCESS even though the file was not successfully restored; i.e., due to a bug in the script.

In general, the pool cannot distinguish between only the file simply not being there (i.e., a simple failure to restore a file) and some deep problem with the underlying file-system.  I've heard of sites having problems with certain attached storage where the pool's files simply disappeared while the pool was running.

Given the above ambiguity, the pool's current behaviour (when told a file was restored but cannot be found) is the safer option.  Indeed, this fail-fast behaviour even allowed you to discover the problem with your script quickly!

**Comment by onnozweers** [comment]
Hi Paul,

OK, that makes sense.

Thanks
Onno
