### ISSUE TITLE
gplazma.x509.use-policy-principals should default to true

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2320]
Either this feature is useless and shouldn't be there anyway... or it should be enabled per default so that sites actually benefit from it, especially since it doesn't seem to be mentioned in the release notes at all.

If it breaks compatibility with 2.14... fine... first I think the native way is rather to assume that all nodes run the same version, so I don't see why such sites should suffer because of sites who don't do so.
Second, the proper way would be a release notes entry, telling people "hey there is this new thingy, but it will break if you run mixed post 2.14 with 2.14... in that case please set foobar=baz".

Cheers,
Chris.

**Comment by calestyo** [comment]
Oh I messed up 2.14 with 2.13 O:-)

**Comment by gbehrmann** [comment]
Two golden releases following each other maintain backwards compatibility. Period. There is nothing to discuss.

Once we get past a golden release and compatibility with older pools is no longer required, defaults are changed. You may want things to change faster, but most sites actually want things to go slower. If you don't like it, you are welcome to fork. 

The proper way is a release notes entry announcing a new feature and another release notes entry in a later release announcing that a new feature is now considered stable and enabled by default. It is a waste of our time having to help debug every site that breaks upon upgrade due to incompatibilities like these.

Yes, NDGF is one of the main sites running with mixed pools, but we also pour significant funding into the development of dCache. One of the benefits is that we get direct influence on how things are run.
