### ISSUE TITLE
Issuing "save" duplicates some statements in poolmanager.conf

### ISSUE THREAD

**Issue by jstarek** [dCache/dcache#2384]
On a recent trunk build, 2.16@ce8e36921ceb0afa14e90b7a82b01906c95a6071, we observed that issuing the "save" command in the PoolManager admin shell will duplicate entries in /var/lib/dcache/config/poolmanager.conf.

Steps to reproduce:

- Install and configure a single-instance dCache. (My pool is connected to EuroGate as a simulated HSM, I'm not certain if that's connected to the issue).
- Start dCache.
- Take a snapshot of /var/lib/dcache/config/poolmanager.conf.
- Log in to the admin shell.
- \c PoolManager
- save
- exit admin shell
- compare /var/lib/dcache/config/poolmanager.conf to snapshot from earlier: All psu statements got duplicated.

**Comment by kofemann** [comment]
UniversalSpringCell calls printSetup for each bean which implements CellSetupProvider. In poolmanager.xml we create two beans: psu and PsuAccess. The second one is a decorator around psu. As a result, printSetup called twice.

**Comment by alrossi** [comment]
I'll take a look to see what the best solution is.  Maybe the decorator isn't needed after all.

**Comment by alrossi** [comment]
I think it is as simple as eliminating the call to the delegate in the PsuAccess.  I had already done this in the beforeSetup and afterSetup methods, just forgot to do so here.

**Comment by kofemann** [comment]
or we have to ensure that one one of them implements  CellSetupProvider

**Comment by alrossi** [comment]
It actually is useful to have the decorator know about startup, because it sets an internal flag.  So beforeStartup and afterStartup need to be there.  the decorator should just not touch the delegate, which is the implementation, which already takes care of this.   I don't know whether it would be desirable to take that interface off of the psuV2 class, but if so, we could just move it into the decorator.   

But for now the double def is OK I think.
