### ISSUE TITLE
Disable OCSP by default

### ISSUE THREAD

**Issue by gbehrmann** [dCache/dcache#2474]
Word has it that WLCG isn't ready for OCSP. We have had at least one incident in which OCSP brought down dCache at sites. It has been suggested that we disable OCSP in our default configuration.

**Comment by paulmillar** [comment]
Yes, but we should open ticket(s) since IGTF promised (me, at least) that all CAs that include a OCSP endpoint in their CA are running a production instance.

That said, I think there's a deeper issue here.  OCSP is an online query; there is always the possibility of network delay.  dCache should handle such problems better.  For example, if the OCSP endpoint of CA-1 is slow, then users of CA-1 should experience this "pain", while users of CA-2 (which has a responsive OCSP endpoint) should not see any problems.

Such behaviour likely requires changes to the CANl API, but perhaps we can work with them on that.

**Comment by gbehrmann** [comment]
Even production instances can have problems. If a firewall blocks access to the OCSP endpoint (as happened with the CERN CA), then there is not much the IGTF can do. Don't know what the point of a ticket should be.

It should be a conscious decision by the admin of dCache to make it depend on an external service, hence this request to change the default.

**Comment by paulmillar** [comment]
IGTF could provide centralised monitoring of their CA OCSP endpoints, and alert the CA when there is a problem.  They could insist on CAs providing such monitoring internally and include this as part of their audit.

I only half buy the "external service" argument; but, by that logic, checking CRLs should also be disable by default.  That service, too, can be (and has been) broken.

Really, I think this comes down to IGTF saying CAs must provide a production ready service if they include OCSP in CA certificate.  If we disable support, we implying we don't believe this to be true.  The ticket would be against IGTF about (apparent) policy violation.

**Comment by gbehrmann** [comment]
Your argument about CRLs is broken since dCache isn't fetching any CRLs - we are not relying on an external service. The admin explicitly needs to install fetch-crl to get CRL verification.

**Comment by gbehrmann** [comment]
You are most welcome to open a ticket with the IGTF though, citing the incident with the CERN CA in April.
