### ISSUE TITLE
ByteUnit fail with ArithmeticException

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#2647]
ByteUnit defines methods like

int toBytes(int)

which fail to convert expression

GiB.toBytes(2);

Caused by: java.lang.ArithmeticException: Out of range: 2147483648
        at org.dcache.util.ByteUnit.checkedCast(ByteUnit.java:1128)
        at org.dcache.util.ByteUnit.toBytes(ByteUnit.java:1163)

as it tries to cast result to int. All toXXX methods must return longs even if they take in as an argument.

**Comment by gbehrmann** [comment]
I think this behaviour is documented in the JavaDoc. The correct call would be `GiB.toBytes(2L);`.

**Comment by kofemann** [comment]
I em not sure that javaDoc some how mentioned it:

https://github.com/dCache/dcache/blob/7b770bced8c87384cb05082483f69ffe29f0d3cf/modules/common/src/main/java/org/dcache/util/ByteUnit.java#L1158

GiB.toBytes(2L); 

is a way to get it to work, but not intuitive at all.

**Comment by gbehrmann** [comment]
The JavaDoc of the class: https://github.com/dCache/dcache/blob/7b770bced8c87384cb05082483f69ffe29f0d3cf/modules/common/src/main/java/org/dcache/util/ByteUnit.java#L42

As for unintuitive, I might agree with you on that. We need Paul to comment on his rational for this choice, but it does at least appear to be intentional.

**Comment by paulmillar** [comment]
One of the design goals behind ByteUnit is that we don't get "mysterious" failures due to scaling; e.g., casting a long to an int could result in negative values.  In general, we can't solve this as its a feature of Java; however, we can improve the situation by "moving the cast" into the method.

To this end, we have two integer GiB.toBytes methods: one that returns an int and one that returns a long.  Both versions throw ArithmeticException rather than returning a wrong value.

Since Java doesn't support overloading methods based on their return type, I decided to go for a convention where the input type determines the return type: int in -> int out, long in -> long out (and also double in -> double out).

So, GiB.toByte(2) fails, as intended, as 2 GiB cannot be represented by a int value.  GiB.toByte(2L) is the correct way of expressing this if the code is expecting the answer to be a long.

**Comment by paulmillar** [comment]
Does my explanation make sense?

**Comment by kofemann** [comment]
I can live without it.
