### ISSUE TITLE
Cleaner does no use password file

### ISSUE THREAD

**Issue by IATkachenko** [dCache/dcache#2928]
There is no option for cleaner to use password file for access to database, 
It have just:
_/usr/share/dcache/defaults/cleaner.properties_
`
(immutable)cleaner.db.host=${chimera.db.host}
(immutable)cleaner.db.name=${chimera.db.name}
(immutable)cleaner.db.user=${chimera.db.user}
(immutable)cleaner.db.password=${chimera.db.password}
(immutable)cleaner.db.url=${chimera.db.url}
`
So we have to store database password in dCache config.

**Comment by rptaylor** [comment]
I figured out how to use these password files, it is a very nice feature.
(Same syntax as .pgpass, chmod 600 and chown dcache.dcache)

However the implementation is incomplete - in addition to cleaner.db.password.file , the following properties are also missing:

star.db.password.file
alarms.db.password.file
httpd.alarms.db.password.file 

It would be very useful to complete the implementation of the password.file mechanism so that passwords can be fully removed from config files.

**Comment by rptaylor** [comment]
Annoyingly, cleaner.db.password is immutable (v3.2) so you have to go back to using chimera.db.password anyway.

**Comment by rptaylor** [comment]
Hi Paul, thanks for the background info, that makes sense. No not at all, it was only annoying in the sense that it blocked me from expunging passwords from config files (which I initially thought would be possible based on chimera.db.password.file). Just testing on dev system of course :)

Yes, it would be very nice to complete this process by adding the missing properties. Thanks for looking into it!

**Comment by rptaylor** [comment]
@paulmillar   can cleaner.db.password.file be implemented, with default value chimera.db.password.file , to complete the removal of passwords from config files?

**Comment by kofemann** [comment]
https://rb.dcache.org/r/12485/
