### ISSUE TITLE
does dCache use ACLs in Zookeper?!

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3365]
Hey.

Just wondered, does dCache use ACLs in ZooKeeper? If not (which I assume, since it's anyway completely unauthenticated),... shouldn't we suggest people in the docs to set `skipACL`, which according to the documentation:

> results in a boost in throughput

Cheers,
Chris.

**Comment by calestyo** [comment]
Similarly,...
In the embedded ZK, you set:
zookeeper.max-client-connections = 1000
while for the standalone server the default is 60.

Does a single client (i.e. IP address) really make that many connections (i.e. >60)? If this is usual for dCache (I don't know), then the wiki (and the release notes) - which both heavily suggest people to use the standlone ZK server - should probably tell people to set:
`maxClientCnxns=1000`

Right? :)

**Comment by paulmillar** [comment]
You're correct: dCache does not use authentication when communicating with ZooKeeper; partly, because the ACL support in ZooKeeper is currently a bit messy (e.g., changing a password requires changing all ACLs for that user) and partly because we imagine dCache will be working with a dedicated ZooKeeper instance.

Therefore, I believe you are right: adding the `skipACL` option should not prevent dCache from working, but may yield some performance improvements.  We can maybe provide this as a hint somewhere.

AFAIK, the `zookeeper.max-client-connections` is simply set to a large enough number that this is unlikely to cause a problem; however, I think you're right: we should provide some guidance here, too.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10401/

**Comment by calestyo** [comment]
Nice :-)

Can I (or you) copy this over to https://github.com/dCache/dcache/wiki/ZooKeeper ? I think many people will have a look there for how to set up their dCache ZK.

Also. can you elaborate on how many ZK connections dCache actually sets up?
Is it like one or a fixed number n per domain? Which would mean that the default of 60 is likely enough for most sites.
Or does it scale up with the number of cells running in a domain?

Cheers,
Chris :-)

**Comment by paulmillar** [comment]
Each domain will make a single connection to zookeeper.  It chooses a random endpoint from the connection string; if that fails at any point, another endpoint is used.  If a dCache node hosting _n_ domains and there are _m_ nodes in the zookeeper ensemble, a zookeeper service will typically see _n/m_ connections from this node and (in worse case) _n_ connections.

**Comment by paulmillar** [comment]
Short answer -- unless a site is doing something completely crazy, a limit of 60 will be fine.

Wiki page is updated.

**Comment by calestyo** [comment]
Okay, i'd guessed that already... I think that's valuable information, since it will tell people that the default of 60 is enough for anyone being sane...

Shall I make a pull request or you?

Further, I'd say we can perhaps adapt the default of the embedded one as well?
Literally no site should have more than 60 domains per IP addr and if they do, they can probably live with finding out the hard way.
So I think there is no much reasons that the embedded ZK deviates from the defaults of the standalone here, when all others are in sync :)

**Comment by calestyo** [comment]
I think we could add just what you said:

> Each domain will create exactly 1 connection to a ZooKeeper server. Thus, if a node hosts n dCache domains, in an enseble of m ZooKeeper servers (that are all running) each of them ill see typically about n/m connections per IP address and n at most (e.g. in the case of all other ZooKeeper servers being down).

**Comment by calestyo** [comment]
Oh and one further ZK thing, which I don't want to open a separate ticket about:

AFAIU, ZK itself would support using a **single** domain name for running an ensemble behind (i.e. via DNS round robin).

Of course all the ZKs would need to use the same port in that case and there are the usual issues with DNS TTL when changing the list of servers.
But it may be worth to add guidance about that to the dcache.properties and the wiki as well:
i.e. does that one-round-robin-dns name work with dCache+ZK plus are there any special pros/cons from the dCache PoV.

:-)

**Comment by paulmillar** [comment]
Of course, you should be able to run ZK behind DNS round-robin, or any other load-balancer technology.

However, I think this is delving into too much detail on how to run ZK.  There's nothing dCache specific about this kind of setup, nor are there any dCache-specific problems from doing so.

If you feel this kind of setup should be documented, then please add it to the ZK admin guide -- our wiki page cannot be a replacement for that document!

**Comment by calestyo** [comment]
Well this isn't about re-doing the ZK admin guide... ;-)

Speaking with wearing my admin hat I wouldn't have know for example, whether dcache.zookeper.connection is simply passed through as is (and this thus being a ZK matter, whether it works or not)... or whether you e.g. resolve IPs first for some valid reason, and by that perhaps loose any further IPs from a DNS round robin.

Also, a non-developer doesn't necessarily know whether dCache itself makes any smart use of the dcache.zookeper.connection... maybe there's something like letting local domains try the local host ZK first, if any, and thus a dcache.zookeper.connection hostname matching the local hostname would be needed for this to work.
For a developer, it may be clear out of the box, that this is just a matter of whether ZK itself supports it or not... for the admin, not knowing the code usually, not.

**Comment by paulmillar** [comment]
Hmmm.. no, I really don't buy either argument.

I think it's now pretty clear: in dcache.properties it's described as "ZooKeeper connection string", where "connection string" is a zookeeper-specific term: if you have deployed ZooKeeper, you should know this term.  In the wiki entry, we're even more explicit that this is the connection string, as described by ZooKeeper documentation.  Anyone who believe this is anything other than the connection string (as passed by dCache to ZooKeeper client library) cannot be helped by adding further documentation ;-)

For the second point, this becomes reductio ad absurdum.  In effect, you're asking for a complete functional description of dCache as comments in the properties defaults file; otherwise a lack of information wouldn't imply a lack of use (yes you could say this is only one property, but anyone can point a finger at another property and demand "proper" documentation).  Doing this would be neigh-on impossible; maintaining it would be similarly impossible and if we somehow managed to do it, the file would be unreadable.

Also, if someone seriously believes that maybe, just maybe, dCache is doing something "nefarious" with the string (either parsing it or modifying it) then they need to check the source-code, which they would then need to compile and deploy.  Anything short of that would leave open the possibility of the property being used or modified somewhere.

In the end, admins should configure properties as documented and so that it fits their setup.  If the see problems, they should open a support ticket.  We add documentation to try and keep down the support tickets -- so we don't have to configure each site ourselves.  So far, the zookeeper transition has been largely support ticket free.

Just for comparison, there are the `.db.url` properties.  Like the connection string, they are passed directly to library code and describe how to connect to some resource.  Over the years, we doesn't seem to have had any major problems with them.

**Comment by paulmillar** [comment]
I think the documentation has been updated so that the behaviour is reasonably well described.

Let's close this issue here and re-open it if the updated information proves confusing or incomplete.
