### ISSUE TITLE
please mention new dcache.default-access-latency and dcache.default-retention-policy in the release notes

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3368]
Hey.

In https://github.com/dCache/dcache/issues/3310#issuecomment-314108637 Al pointed me towards the new options `dcache.default-access-latency` and `dcache.default-retention-policy` which apparently (AFAICS since 3.1) now serve as the cluster wide defaults.

Before we only had their pnfsmanager.* counterparts, which people may have set (and perhaps other services picked up?).
Because of that, people should probably be taught to use the new global options, however, AFAICS (flame me if I just missed them) they're no where mentioned in the release notes.

Could you please add this information to the section for the **next** minor release (people won't read the entries for versions they're already beyond - why should they - so they would still never notice it, if you just add it to the version where it was actually introduced.

Speaking of which:
What about maintaining the release notes as part of the dcache repo... ?
- Everytime a commit changes something that should go to the release nodes of the next major, the commit actually doing the change also adds the docs to the respective release notes file as managed in master.
- And everytime something is backported, the cherry-picking commit does the same for the release notes from the respective old versions.

This is how most open source projects I'd know handle that.

Thereby one gets rid of that decoupled developing / documenting... the commiter doing a change is also responsible for its documentation - after all he's probably anyway who knows best what happens.

Changes to the acutal documentation (i..e "the book") could be handled similarly... perhaps it would be a bit unhandy to do it in the very same commits that change the code, but when e.g. some bigger changes are made (like a new service),... there could be a branch with all the commits leading to the implementation of that service... and 1-n amongst them are the ones updating the book.

Cheers,
Chris.

**Comment by paulmillar** [comment]
You're right: the new properties are not properly described in the release notes, although the motivation is there (Chimera CLI can query access latency and retention policy).  This should be updated.

I don't think we should mention the change in the bug-fix release -- it's related in the bug-fix (so would be confusing) and there's no guarantee that an admin will read that particular bug-fix release.

Instead, I'll send an announcement on user-forum that the release notes for 3.1 have been updated.  I think that's the better approach.

Putting the release-notes in the dCache repo -- interesting, although I'm not sure how that would work in practice -- we have a careful procedure for controlling changes with different people taking different responsibility.  Updating both the code and the release-notes at the same time would require a single updated (currently a pull request) with changes from two people (developer and change-log writer).

With the book -- we did discuss doing this; but, in the end, the logistics didn't really make sense.  It turns out that developers write lousy documentation so coupling those two activities doesn't make sense.

**Comment by calestyo** [comment]
> I don't think we should mention the change in the bug-fix release -- it's related in the bug-fix (so would be confusing) and there's no guarantee that an admin will read that particular bug-fix release.

It's up to you in the end, but I think this has the downside, that people may not catch it as well (e.g. I follow user-forum, but it's not that I read every message in detail unless it get's somehow my bigger attention).
The release notes/NEWS file/changelog, should IMO be the "official" and "definite" source for changes.... and not everything scattered over many different places (e.g. an "grolden release upgrade guide" in addition).

IMO, one can expect from an admin, that he reads all the release notes,... full stop. If he/she doesn't do, well then all further things are his/her responsibility.

One way you could handle it, would be adding a point:
"fix missing changelog entries for version <some past version>, [commit id]" ... so people who want to have a look, can see in the commit what was exactly added to the relase notes (which would however require the release notes being git managed).

Well, you can discuss that internally, if you like :-)
But IMO the problem may actually already be, that dev != change-log writer.


As for the changelog writing another idea would be the following:
Right now you have a schema like:

> common:
> - Textual change... bla bla.
> srm:
> - Textual change... foo bar.
> pool:
> - Textual change... baz bar.
> 
> ... further down the road...
> 
> - commit id, commit summary
> - commit id, commit summary
> - commit id, commit summary
> - commit id, commit summary
> 

To be hones, for me this often makes it rather useless, as it's sometimes difficult to correlate the text message to the actual commits corresponding to it.
I think better would be a format like:

> common:
> [commit id]: Textual change... bla bla.
> srm:
> [commit id], [other commit id]:- Textual change... foo bar.
> pool:
> [commit id]:- Textual change... baz bar.

or perhaps:
> common:
> [commit id]:
> - Textual change... bla bla.
>
> srm:
> [commit id], [other commit id]:
> - Textual change... foo bar.
>
> pool:
> [commit id]:
> - Textual change... baz bar.

for better readability.

So that one directly sees, which text news and which commits correspond.
This could be also a first step making the release notes github markdown ;-)

Maybe one could additionally mark, whether an entry was something "new" or a backport.

Right now, I still always go through **all** the release notes of the currently supported versions (i.e. even those that are older than what I already run), cause it still happens from time to time, that things that get into the new entries for new minor releases... are missing in the newer release notes from the newer major versions, but are in the ones for older major versions.


Cheers,
Chris.

**Comment by paulmillar** [comment]
The release notes have been updated.

**Comment by paulmillar** [comment]
I think partly the problem here is you don't see the distinction between the release notes and the commit message -- it's about different audiences.

The commit messages are specifically targeted at developers.  I would guess almost all commit messages would be almost meaningless to almost all admins.  For some patches, it may not even be clear which services are affected (i.e., which machines do I need to upgrade?) without develop-level knowledge of dCache.

The release-notes are specifically targeted at admins, and we try to be consistent in what language we use.  The results of upgrading should be described as admin- or user- observable effects, not internal changes (as with commit messages).  Believe me, it is actually very hard for developers to map the changes they see (dCache internal detail) into user- and admin- observable changes, so provide information that would make sense to an admin.  Requiring all developers to also be release-notes writer would likely result in unreadable release notes.

Additionally, there may be multiple patches that combine to give the desired result.  There are also commits that have nothing to do with released dCache code, but rather about our testing infrastructure.  So the mapping between release-note information and commits is not necessarily one-to-one.

**Comment by calestyo** [comment]
>I think partly the problem here is you don't see the distinction between the release notes and the commit message -- it's about different audiences.

No that's quite clear... but **then** it makes not much sense to have them in the release notes at all -  developer can simply use git / git-tools to query the changelog.


For me as an admin,... when going through the release notes, I rarely have to look at the commits (as you've said)... but every now and then, there's a release note entry, from which I don't understand what's going on there or where I wonder about the deeper things behind... and before annyoing you guys with asking, I look at the commits which sometimes explain things/motivation in more detail or where the code sheds some light.
However, typically it's then already quite some effort to find out to which commits a release note entry actually corresponds.

Anyway... was just an idea =)

**Comment by paulmillar** [comment]
That's great that you feel confident enough to look at the commit messages :-)

However, please feel free to open a support ticket if the release notes are unclear about some point.  We do our best, but ambiguities and mistakes do creep in.

**Comment by paulmillar** [comment]
I think this issue can be closed.  The release notes have been updated and people have been alerted to the updated release notes.

**Comment by calestyo** [comment]
thx =)
