### ISSUE TITLE
Request: frontend setting to disable admin capabilities

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4061]
We'd like to have two dCache Views, one without admin capabilities for the users, and another for us admins, that we can protect with the firewall.

I currently can't see an option that we can use to make such a distinction, though I may have overlooked something. I thought about setting the `gplazma.roles.admin-gid` to a non-existing number, but I guess this disables admin roles for all of dCache, which is not what we'd like.

Would it be possible to have a frontend option that disables admin capabilities (or perhaps "roles" in general) but does provide all the user functionality, so that users can do all these nice things without us having to worry so much about security?

**Comment by alrossi** [comment]
Hi Onno,

This is something we definitely plan to do (I think I may have mentioned it at the workshop ...).

We also want to change the navigation so that the admin navigation bar remains visible at the top of each admin page, so that you don't have to move back and forth to the main 'admin' tab.

I would imagine that for the users not logged in with the admin role, that would mean the navigation bar would simply not be present on the home page.   Haven't worked out the details yet, but this is definitely on the list.

Al

**Comment by alrossi** [comment]
https://rb.dcache.org/r/11070/
https://rb.dcache.org/r/11091/

**Comment by alrossi** [comment]
The toolbar will be addressed later.
