### ISSUE TITLE
alarms: NPE when sending an alarm

### ISSUE THREAD

**Issue by ahaupt** [dCache/dcache#4461]
dCache version 4.2.18

When sending an alarm via the alarm service:

```
[trajan-vm2] (alarms@alarmDomain) admin > send "Test alarm"
sending alarm to trajan-vm2.zeuthen.desy.de:9867
```
... a backtrace in alarms log file is produced:

```
26 Nov 2018 13:43:49 (alarms) [] Uncaught exception in thread pool-5-thread-1
java.lang.NullPointerException: null
	at org.dcache.alarms.logback.LogEntryHandler$LogEntryTask.run(LogEntryHandler.java:148) ~[dcache-core-4.2.18.jar:4.2.18]
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251) ~[dcache-common-4.2.18.jar:4.2.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

... and no mail is sent although mail sending is enabled here. This bug looks similar to #2578

**Comment by alrossi** [comment]
Andreas,

I think your problem is independent of the MDC issue. It has to do with the received field being null (the JAVA autoboxing code will throw an NPE when you do something like this:

Integer i = null;

if (i == 0) {
...
}

and that is what seems to be the case here. However, I am not sure how this is actually occurring.

What database are you using ... RDBMS or XML?

Thanks, Al



________________________________________________
Albert L. Rossi
Application Developer & Systems Analyst III
Scientific Computing Division, Data Movement Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023


________________________________

**Comment by ahaupt** [comment]
Hi Al,

it's the default, so XML. And it gets filled with alarms, so this works.

```
[trajan-vm2] /root # ll /var/lib/dcache/alarms/store.xml 
-rw-r--r--. 1 dcache dcache 970 Nov 26 16:20 /var/lib/dcache/alarms/store.xml
```

Cheers,
Andreas

**Comment by alrossi** [comment]
Hi Andreas,


yes, indeed I can reproduce the issue using XML.


Looks like the XML DataNucleus plugin needs to be retested.


I will investigate.


Thanks, Al


________________________________________________
Albert L. Rossi
Application Developer & Systems Analyst III
Scientific Computing Division, Data Movement Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023


________________________________

**Comment by alrossi** [comment]
The problem is that with the xml plugin, the Java object is forcibly detached after commit (not so with RDBMS), so all its fields are null when referencing it after commit.   

Evidently, we neglected to test the xml option after the most recent upgrade of DataNucleus which apparently modified this behavior.

I have posted as fix:  https://rb.dcache.org/r/11398/
