### ISSUE TITLE
Request: make message "Failed to cancel task" more informative

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5185]
Dear dCache devs,

While trying to rebalance pools and checking `migration info rebalance`, I got this:

```
Most recent errors:
08:35:39 [2] 000002B705B04DB74DF3ADA92C129D931DF0: Failed to cancel task
08:40:51 [3] 0000AF0A17D379924C5B9A1D6C2279A81EB8: Failed to cancel task
08:43:48 [4] 00005791755077314918A66DE3630171D27B: Failed to cancel task
08:43:58 [5] 0000ED014DD7081A41C6BC287C05E6509F25: Failed to cancel task
08:45:47 [7] 0000BE5ABF013784440B8C25BFA86F230051: Failed to cancel task
08:48:18 [8] 0000DE9EB3BF57A741BA8C9473ED50F5C380: Failed to cancel task
08:48:29 [9] 0000A10998F5C6BB45D084A609CCA354FD3B: Failed to cancel task
08:48:39 [10] 0000437F67EFAF644D4D8F5B0F7A22509CC9: Failed to cancel task
08:48:49 [11] 00005ED09194C39A4649A12ACABFE5737E4F: Failed to cancel task
08:52:24 [13] 0000475DE2ADE7E040D9BA18724D60B0AF24: Failed to cancel task
08:52:34 [14] 00001D4974092DF546439DF9200636417BDC: Failed to cancel task
08:52:44 [15] 00002C566AA4FA3F4D1BA718DD115F1D1E2F: Failed to cancel task
08:57:53 [16] 00009915D900C858449096AF63057515595C: Failed to cancel task
09:04:46 [18] 00006071AD8E5B394AD9808DA262E3D3657A: Failed to cancel task
```
This is very unclear to me. Why did it fail? Why was the task being cancelled in the first place?

From the source I could not understand in which case this message is generated. Could this error perhaps be rephrased to give some clues about what might be wrong?

Cheers,
Onno

**Comment by paulmillar** [comment]
I agree, this is quite confusing and I'm working on a patch to make this clearer.

The message `Failed to cancel task` is recorded when an attempt is made to cancel migration module's movement of a file, but stopping the process was not possible because the file has pins and either the pins haven't been moved or are currently being moved (which involves communicating with PinManager).

This then prompts the question: why was these tasks being cancelled?

There's a few possibilities: the file was deleted or the conditions of the pool changed so that file should no longer be migrated.  Since these tasks come from the rebalancer, there could also have been an admin command (`rebalance pgroup` or `rebalance cancel pgroup`) that triggers migration model job cancellation.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/12064/

**Comment by paulmillar** [comment]
Hi Onno,
Would you be willing to deploy a custom version of dCache that provides more information about what is going on?
This should help identify why you are seeing migration tasks being cancelled.

**Comment by onnozweers** [comment]
> Hi Onno,
> Would you be willing to deploy a custom version of dCache that provides more information about what is going on?
> This should help identify why you are seeing migration tasks being cancelled.

I will try to make some time available to install the latest snapshot and try and reproduce the issue.
