### ISSUE TITLE
JDK 11 gPlazma memory issue again

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5202]
Hi Tigran,

Last Tuesday we have upgraded OpenJDK to 11 on the node running gPlazma (5.2.8). But now we have a memory issue again (#5077):

```
[19497.011s][warning][os,thread] Attempt to protect stack guard pages failed (0x00007fcc4c65c000-0x00007fcc4c660000).
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fcc4c55b000, 16384, 0) failed; error='Not enough space' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 16384 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /usr/share/dcache/hs_err_pid19010.log
```

The mentioned file, and the gPlazma log including thread dump, you can download from https://surfdrive.surf.nl/files/index.php/s/grS8Veq0vhEFht3, the password is Patrick's last name.

For now I'll downgrade OpenJDK on the gPlazma host to 8 to work around the authentication failures.

**Comment by paulmillar** [comment]
Hi Onno,

Thanks for reporting this.  Unfortunately, the JVM failed to allocate memory, rather than dCache running out of memory.  This means we don't have a heap dump to figure out where all the memory has gone.

You seem to have configured this domain to have 10 GiB -- somehow it seems this machine doesn't have all this 10 GiB to give to the JVM.

Would it be possible to run the domain with a smaller memory size?  That way, the domain should crash with the Java out-of-memory error, creating a heap dump file .hprof.

Cheers,
Paul

**Comment by onnozweers** [comment]
Hi Paul,

I'm a bit puzzled now... It appears the machine does have enough memory, or my understanding of Java memory management is insufficient.

```
[root@dcmain ~]# free -h
              total        used        free      shared  buff/cache   available
Mem:            62G         19G         15G        1.1G         26G         41G
Swap:           15G          8K         15G
```

Cheers,
Onno

**Comment by paulmillar** [comment]
There's two things in play here: the memory that Java (believes) it has and the memory of the system in general.

By default, dCache domains are configured to use an explicit amount of memory from the OS.  This is 512 MiB by default, but may be configured using the `dcache.java.memory.heap` configuration property.

This means that the running Java code has, at most, this much memory with which to work.  If dCache code (or libraries) exhaust that memory, the JVM will die with an OutOfMemoryError.  Due to our JVM configuration, an OutOfMemoryError will also result in a heapmap being logged.   This allows us to try to figure out what was using all that memory.

However, the JVM does not allocate all that memory from the OS on start-up.  Instead, it tends to allocate memory as it needs it, up to the configured maximum value.  So, if the amount of memory the JVM believes it has exceeds what is actually available, the JVM will crash when it comes under (internal) memory pressure and it tries to allocate more memory from the OS.

This is the JVM itself running out of memory, rather than the Java code.  Such a crash will not generate an OutOfMemoryError, but rather a `hs_err_pid<PID>.log` file.

In Java there are two types of allocatable memory: heap and direct.  Direct is memory that is addressable by non-CPU devices (e.g., harddisk) for DMA, and is usually a rarer commodity.  I believe the JVM will crash under memory pressure if either memory is overcommitted: if the JVM is configured to make available more memory that the system actually has.

So, one way forward is to reduce the memory dCache is configured to use, for the domain hosting gPlazma.  This will not solve the problem, but might allow the JVM to allocate all the configured memory.  With a reduced memory footprint, a domain will fail with OutOfMemoryError, and so yielding a heapmap.  This should then give us more of a clue what is going wrong.

**Comment by kofemann** [comment]
After some investigation, indeed looks like LdapLoginModule, which is used by gplazma plugin leaks a thread on each login.

I will try to make a testcase and report to OpenJDK. As a fix for java11 is not expected in near future, gPlazma is updated to use an alternative approach:

https://rb.dcache.org/r/12405/

**Comment by onnozweers** [comment]
After 5 hours of running gPlazma on OpenJDK 11, it had >10k threads. An `explain login` that needed to query our LDAP service, took 4m and 22 secs. After restarting, it took 0.2 seconds. I think we need this patch 😸

**Comment by kofemann** [comment]
Turned you that issue it not observed with java-14. The is probably released to

http://hg.openjdk.java.net/jdk/jdk/rev/6717d7e59db4

I wrote an e-mail to JDK developers. Let see what they say.

**Comment by kofemann** [comment]
It looks like java 11.0.8 should contain the fix:

https://bugs.openjdk.java.net/browse/JDK-8237876

**Comment by onnozweers** [comment]
Hi Tigran,

Thanks, that is good news! The Centos repos now have 11.0.7, I wonder when 11.0.8 is due.

I noticed there is also JDK 14 in the repos:

```
java-latest-openjdk.x86_64 : OpenJDK Runtime Environment 14
```

Shall we try that? Could it have a beneficial effect on our performance issue? Tomorrow we have another downtime so we can make changes.

Yesterday we ran JDK11 for a few hours, which seemed to perform slightly better than JDK8: the load was half, the CPU 10% less than with JDK8. We had to downgrade because the gPlazma-LDAP popped up again.

Kind regards,
Onno

**Comment by kofemann** [comment]
According to java11 release schedule[1], 11.0.8 expected on July 14 2020.
We will proceed with our workaround.

-kofemann
/** caffeinated mutations of the core personality */

[1]: https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u

**Comment by kofemann** [comment]
The java 11.0.8 is released and contains the fix of connection leak

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8217606

Hopefully this issue is finally resolved.

**Comment by kofemann** [comment]
Test case is added to dCache code base ce8b186e97

**Comment by onnozweers** [comment]
Thanks Tigran!
