### ISSUE TITLE
API: SSE listener resuming from last event ID?

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5316]
Dear dCache devs,

We've noticed that if you start listening to a channel, any existing listener is thrown out. That's not really a problem, we can work with that.

But there might be a case when a listener crashed and is restarted; in that case some events may get lost in the meantime. Now, we've discovered the option to resume from a certain event ID. However, the burden of not missing any events is then left to the user. Users will need to be made aware of this.

Since there can be no more than one listener to a channel anyway, we can imagine it's possible to let dCache keep track of which event was last listened to, and then, if listening resumes, automatically resume from there. That would make it easier for a listener to not miss any events.

What would you think?

Cheers,
Natalie & Onno

**Comment by paulmillar** [comment]
Hi Natalie & Onno,

The original (and current) concept is that each client creates its own channel.  A user might have multiple clients; therefore, a user may have multiple channels.  However, each channel is servicing events to a single client.  To re-enforce this idea (single client per channel), any client connecting to a channel will kick out an existing connection.  This is the behaviour you observed.

(I'm currently rethinking whether this is the best option.  There's some technical benefits to limiting a channel to a single client, but I'm reconsidering the trade-offs and might change this in the future.)

For the last-event ID, yes, you're correct that this places the burden on the client.  However, this behaviour comes from the SSE standard:

    https://www.w3.org/TR/eventsource/

Although the user can obtain events using a simple HTTP client (such as curl), there are many SSE clients that will automatically reconnect without loosing events from simple network problems:

    https://en.wikipedia.org/wiki/Server-sent_events

These libraries may need some addition configuration to support reconnecting if they die unexpectedly; for example, they may need some external storage (a temporary file) in which the channel URL and last ID are recorded.

I was expecting that people would use one of these standard clients when consuming dCache events (rather than using curl), so it would be helpful if you could try them out and let people know how you get on.

You mentioned the idea of keeping track (in dCache) of which events a client has consumed, so that the client doesn't need to remember this information.  Unfortunately, with the SSE protocol, dCache can only know that the event was placed on the server's TCP output buffer, not that the client received the event, and not whether the client processed the event.

This problem could be solved by the client providing explicit, continuous feedback, where the client acknowledges an event once it has processed it.  This is the model used by the Apache Kafka software.  However, to implement this would require changing the network protocol into something incompatible with the SSE standard.

Therefore, without some concrete feedback from the client (either the Last-Event-ID header on reconnect or explicit event-consumed feedback from the client), there's the risk of the client missing some events (perhaps even seeing some events twice).

As an aside: in case you don't already know, there is SSE support in all main-stream web browsers.  A simple demo page is included with dCache frontend that uses this: https://frontend.example.org/events.html.  There is also some python example code available here:
https://github.com/paulmillar/dcache-sse

Cheers,
Paul.

**Comment by onnozweers** [comment]
Hi Paul,

I hadn't realized the SSE standard requires the client to keep track of the last event ID. Of course we don't want to deviate from the standard. We'll solve it on the client side.

I had already discovered the events.html, which was very helpful.

Cheers,
Onno
