### ISSUE TITLE
leftovers in /upload

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#5425]
Hi

I've just noted that there must be cases where dCache doesn't clean up files and/or directories in /upload.

First we had some ~20k empty UUID dirs in it, all from 2018/2019.

But there are also dirs with files from this April, which are apparently leftovers (maybe from failed transfers?).

Cheers,
Chris.

**Comment by paulmillar** [comment]
dCache *should* always clean up these directories, even if the transfers fail or the SRM upload times out (because the SRM client forgot about it, died, ...).

From what you say, it sounds like these left-over directories appear over time in clusters.

Does the problem correlate with dCache upgrades or other dCache administrative interventions?

If not then that suggests some external (to dCache) influence or change in environment is triggering this problem.

Just on the off-chance, is there anything you can think of that changed around the times when these problems started or stopped?

Also, could you track down a few of these transfers where the upload directory isn't cleared and find out any details about them?

Perhaps there is some common factor that they share, which is missing from the transfers that are correctly cleaned up.

**Comment by calestyo** [comment]
Unfortunately I had cleaned everything up, right after I've noticed it. So... it's a bit hard now.

From what I remember I wouldn't say there were any specific upgrades or other intervention... maybe it was rather some dcache versions were it was more likely to happen?

So far there are no new leftovers. But I've heard from MPCDF, that they've also found a few.


Maybe dCache should just get some clean up task that deletes everything older than 14 days every now and then?

**Comment by paulmillar** [comment]
> So far there are no new leftovers

OK, then let's close this ticket.  Please feel free to open it when you have new examples.

> I've heard from MPCDF, that they've also found a few.

Please encourage them to open a support ticket (email <support@dcache.org> or open a github issue).

> Maybe dCache should just get some clean up task that deletes everything older than 14 days every now and then?

We sort of already have this, although it uses information in the SRM database rather than the filesystem.

If directories are leaking then it points to a problem in the database (uploads are being removed from the database without the corresponding cleaning activity) or the cleanup task isn't running.  Stale `/uploads` directories are just one problem; there may be others.  For example, stale entries in space reservations.  Therefore, I would prefer to fix the cleanup problem, rather than introduce a work-around that deletes old directories in the namespace.
