### ISSUE TITLE
Solo HA-cleaner become FOLLOWER role

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#5475]
In a all-in-one setup (system-test) clean become a follower role:

```
[nairi] (cleaner@dCacheDomain) admin > info
--- disk-cleaner (Disk Cleaner removes files from corresponding pools and then from DB as well) ---
Disk Cleaner Info : 
Refresh Interval: 120
Refresh Interval Unit: SECONDS
Cleanup grace period: -
Reply Timeout:  100
Number of files processed at once:  500
Delete notification targets:  [[>PinManager@local], [>SpaceManager@local]]

--- ha-service-leadership-manager (Manages leadership coordination for HA services) ---
HA role: FOLLOWER

--- hsm-cleaner (Hsm Cleaner removes files from HSM) ---
HSM Cleaner Info : 
Timeout for cleaning requests to HSM-pools: 120
Timeout Unit for cleaning requests to HSM-pools: SECONDS
Maximal number of concurrent requests to a single HSM:   100
Maximum number of files to include in a single request:   100
Delete notification targets:  [[>PinManager@local], [>SpaceManager@local]]

```

The participants
```
[nairi] (cleaner@dCacheDomain) admin > ha show participants 
Participant{id='cleaner@dCacheDomain', isLeader=true}
Participant{id='cleaner@dCacheDomain', isLeader=false}
```

[nairi] (cleaner@dCacheDomain) admin > 

Running cells:
```
[nairi] (cleaner@dCacheDomain) admin > \l
acm
alarms
billing
cleaner
DCap-auth-nairi
DCap-gsi-nairi
DCap-nairi
Frontend-DR-nairi
Frontend-NA-nairi
Frontend-nairi
Frontend-S-nairi
Frontend-UR-DR-nairi
FTP-nairi
FTPS-nairi
GFTP-nairi
gPlazma
history
info
NFS-nairi
PinManager
PnfsManager
pool_read
pool_res1
pool_res2
pool_res3
pool_sm
pool_write
PoolManager
RemoteTransferManager
Resilience
SpaceManager
SRM-nairi
SrmManager
topo
WebDAV-DR-nairi
WebDAV-NA-nairi
WebDAV-nairi
WebDAV-S-nairi
WebDAV-UR-DR-nairi
Xrootd-gsi-nairi
Xrootd-nairi
zookeeper

[nairi] (cleaner@dCacheDomain) admin > 
```

znode **/dcache/cleaner/leader**
```
[nairi] (System@dCacheDomain) admin > zk ls /dcache/cleaner/leader
_c_77461ee0-1d24-44bb-8544-5f1f57cbe002-latch-0000000009
_c_4ac10daf-7ce3-4496-8cd2-d67c441655c9-latch-0000000003
[nairi] (System@dCacheDomain) admin > 
```
and the content
```
[nairi] (System@dCacheDomain) admin > zk get /dcache/cleaner/leader/_c_77461ee0-1d24-44bb-8544-5f1f57cbe002-latch-0000000003
(0) Failed to get zookeeper node data: KeeperErrorCode = NoNode for /dcache/cleaner/leader/_c_77461ee0-1d24-44bb-8544-5f1f57cbe002-latch-0000000003
[nairi] (System@dCacheDomain) admin >
```
Looks like after restart leader election thinks that there is some one else is leader, though it the same cell.

**Comment by kofemann** [comment]
Removing one of the znodes have triggered leader re-election
```
delete /dcache/cleaner/leader/_c_4ac10daf-7ce3-4496-8cd2-d67c441655c9-latch-0000000003
```

```
03 Jul 2020 21:03:56 [System-0-EventThread] [] HA: Assuming leader role.
03 Jul 2020 21:05:56 [pool-202-thread-2] [] *********NEW_RUN*************
03 Jul 2020 21:05:57 [pool-202-thread-2] [] runDelete(): Now processing pool pool_write
03 Jul 2020 21:05:57 [pool-202-thread-2] [] Removing files deleted before 2020-07-03 21:05:57.043572 from pool pool_write
```

**Comment by lemora** [comment]
It seems like this issue might be a bug in ZooKeeper, which should delete ephemeral nodes that have no active session attached. Although there are no pings sent for such a non-active session, which is the owner of the ephemeral node that takes part in and wins the leader election instead of the cleaner cell, the ephemeral node is not deleted. I have not yet found a way to circumvent this problem from the client side and opened an issue in the ZooKeeper Jira page (issues.apache.org/jira/browse/ZOOKEEPER-3890).

**Comment by paulmillar** [comment]
This sounds familiar.

We have had the same problem with space-manager in the past.  It used ZK-based leader elections to choose which space-manager instance should clean up the database.  Sites reported problems where this stopped happening.

The problem was due to the domain's ZK session expired, but the space-manager's ephemeral node was not removed.  This meant a space-manager that was no longer running was the "leader".  Manually removing the zombie ephemeral node "fixed" the problem. One of the live space-managers was elected and leapt into life, tiding up the database.

Ultimately, this problem went away, when we stopped using ZK leader elections in space-manager :wink:

**Comment by lemora** [comment]
Do you know, by any chance, if this occurred for both a standalone ZooKeeper (/cluster) as well as the embedded ZooKeeper cell? I have so far only been able to reliably reproduce it in the embedded variant and likely recently identified the cause, which seems to be due to one of our issue workarounds. It is possible that the ZooKeeper code was changed in a way that newer versions do not display such erroneous behaviour anymore and only our self-fabricated one remains, or that it was always the sole issue -- but I remember to have come across vague reports for standalone variants as well, that unfortunately were not further investigated but might be due to similar problems.

**Comment by lemora** [comment]
https://rb.dcache.org/r/12520/

**Comment by kofemann** [comment]
The fix should be backported into all stable branches.

**Comment by vokac** [comment]
Do you think this could also solve issues observed in #5253 / #5356?

**Comment by paulmillar** [comment]
@vokac I think this is unlikely.  The problem was present only when dCache started up.

These other two issues are present once dCache is (otherwise) happily running.

**Comment by lemora** [comment]
@vokac No, I don't think so either. Additionally, this fix is only related to the embedded ZooKeeper, which did not correctly read in the remembered sessions on startup, whereas the other issues relate to any ZooKeeper instance expiring sessions from clients that have not shown signs of life for a while. It might be fixed by another, older patch, however.
