### ISSUE TITLE
Possible race in NFS with small files restored and p2p'd

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#5581]
Testing with the following poolmanager.conf setup:
```
psu create pgroup stage-group
psu addto pgroup stage-group dcatest08-7
psu addto pgroup stage-group dcatest09-7

psu create pgroup tape-group
psu addto pgroup tape-group dcatest03-7
psu addto pgroup tape-group dcatest04-7

psu create link stage-link any-protocol tape world-net
psu set link stage-link -readpref=0 -writepref=0 -cachepref=10 -p2ppref=10 -section=stage
psu addto link stage-link stage-group

psu create link tape-link any-protocol tape world-net
psu set link tape-link -readpref=10 -writepref=10 -cachepref=0 -p2ppref=10 -section=stage
psu addto link tape-link tape-group
```

That is, a stage group which is not readable or writable but is for caching; and a tape group which is not used for staging.

The expected behavior when a NEARLINE CUSTODIAL file has no disk copy is for it to be read back to a stage pool and then p2p'd to the tape pool, leaving two cached replicas.

If a very small file is used, however, it would seem that the NFS door triggers an additional p2p.

Procedure:
```
[arossi@fndcatemp1 tape]$ grep "" $(cat ".(tags)()")
.(tag)(AccessLatency):NEARLINE
.(tag)(file_family):dcache-devel-test
.(tag)(file_family_width):10
.(tag)(RetentionPolicy):CUSTODIAL
.(tag)(storage_group):tape
```

1.  copy 1b 0-filled file
```
[arossi@fndcatemp1 tape]$ cp ~/data/data_1b data-`date | tr ' ' '.'`
```

2.  wait for it to flush, then purge the pool

```
dcatest04-7:
    0000B3EA57D045994EFF967C84CA471BC0F0 <-P---------L(0)[0]> 1 si={tape.dcache-devel-test}
dcatest04-7:
    0000B3EA57D045994EFF967C84CA471BC0F0 <C----------L(0)[0]> 1 si={tape.dcache-devel-test}
[fndcatemp2] (local) admin > \s dcatest04-7 sweeper purge
Purging all removable files from pool.
dcatest04-7: OK
```

3.  capture log INFO

```
[fndcatemp2] (local) admin > \s PoolManager log set stdout INFO
```

4.  Read the file through NFS:

```
[arossi@fndcatemp1 tape]$ cat data-Fri.Oct.16.11\:23\:07.CDT.2020 
```

5.  There are three copies instead of two:

```
dcatest04-7:
    0000B3EA57D045994EFF967C84CA471BC0F0 <C-------X--L(0)[0]> 1 si={tape.dcache-devel-test}
dcatest08-7:
    0000B3EA57D045994EFF967C84CA471BC0F0 <C-------X--L(0)[0]> 1 si={tape.dcache-devel-test}
dcatest09-7:
    0000B3EA57D045994EFF967C84CA471BC0F0 <C-------X--L(0)[0]> 1 si={tape.dcache-devel-test}
```

An extra p2p.  What is strange is that this is a p2p not to the readable pool, but the stage pool.  See attached log.  

If we increase the file size, or use a different protocol to read the file (e.g., xrootd), the restore + p2p leaves only two cached replicas, as it should.

PoolManager grepped at INFO level on 0000B3EA57D045994EFF967C84CA471BC0F0

[0000B3EA57D045994EFF967C84CA471BC0F0.txt](https://github.com/dCache/dcache/files/5393044/0000B3EA57D045994EFF967C84CA471BC0F0.txt)

**Comment by paulmillar** [comment]
I think the problem is that `stage-link` has a non-zero value for `p2ppref`.  This means the pools linked to via `stage-link` are available for p2p targets.

I imagine you've configured the namespace, and defined unit and ugroups so that both `stage-link` and `tape-link` are available when reading the file via NFS.  Both have the same p2p preference, so pool-manager considers both links equivalent and pool-manager chose the `stage-link` pools as the p2p target.

If this is the problem, you should make the `p2ppref` in `stage-link` zero, to exclude those pools as p2p targets.  This should result in only two replicas being created.

Note: the default p2ppref for a link is -1, which means something like "use same value as readpref".  Using this default value, `stage-link` would have p2ppref of zero (as readpref is also zero).

**Comment by alrossi** [comment]
Thanks, I'll give that a try.   Although as I said I did notice that NFS was susceptible to this with small files but it wasn't happening in general.  Then again, that could just be a general timing issue.
