### ISSUE TITLE
GSI with xrootd is documented as not secure

### ISSUE THREAD

**Issue by rptaylor** [dCache/dcache#5845]
Hello,

https://dcache.org/old/manuals/Book-5.2/config-xrootd.shtml#strong-authentication

https://dcache.org/old/manuals/Book-6.2/config-xrootd.shtml#strong-authentication

> SECURITY CONSIDERATION
> In general GSI on xrootd is not secure. It does not provide confidentiality and integrity guarantees and hence does not protect 
> against man-in-the-middle attacks.

Can the documentation perhaps elaborate on how it is not secure?  At this point all sites (for ATLAS anyway) are expected to expose authenticated read/write xrootd access to the world using GSI so it seems like a concern if this is not secure.  Is the documentation out of date?

Thanks.

**Comment by paulmillar** [comment]
The GSI security model in xroot protocol is based (very strongly) on the SSL/TLS handshake.

Glossing over some details, it basically boils down to this...

Under SSL/TLS, the handshake provides some guarantee of the peer's identity: either the client knows the server's identity (if only server presents a certificate) or there is mutual authentication (if both parties present certificates).  In the grid community, we normally use client certificates, so both parties should know the identity of their remote peer.

However, this identity needs to be "bound" to subsequent communication.  In TLS/SSL, this is normally done by establishing a shared secret between the client and server as part of the handshake and then encrypting (or possible just cryptographically signing) messages between the parties.  This guarantees that the message the server receives really came from the client (who's identity the server knows) because only the client knows the shared secret.

(As an aside, the same thing happens in Kerberos: messages are cryptographically signed or encrypted to ensure they really came from the authenticated party.)

In the original xroot protocol, GSI authentication identified the peer through a process very similar to the TLS handshake; however, the subsequent communication continued to be unencrypted and unsigned.  This resulted in the identity NOT being bound the communication.  As a consequence, there are several attack vectors that would allow an attacker to hijack the TCP connection after the GSI handshake has taken place and inject arbitrary commands on the xroot channel.  The server would be unable to distinguish between genuine commands from the client and those from an attacker (hence a MitM attack).

To fix this problem, the xrootd and dCache teams developed and implemented a way of signing xroot commands so that the server can be sure that the client sent the message.  This was designed to be flexible enough that it supports request-signing on specific subset of commands, or to require it on all commands.

This request-signing may become redundant as newer versions of xrootd and dCache support xrootd communication over an encrypted channel, fully using TLS.  In this case, all communication is encrypted (not just signed).  I believe this is largely favoured over request-signing as it will also allow the use of token-based authentication (OAuth2/OIDC tokens following the WLCG AuthZ-WG specificaition).

As an aside, I believe most sites have xrootd and dCache running without requiring request-signing (which would require some effort to enable) and without TLS-encryption (which is newer, and likely requires sites to upgrade).

So, I believe the documentation is incomplete (as it doesn't mention request-signing and TLS-encryption options), but is otherwise accurate.

**Comment by alrossi** [comment]
I would just qualify the above by stating that in 6.2 the documentation for both signed hash verification and TLS is there in that chapter, but the explanation is not unified.  

It would perhaps not be a bad idea to take Paul's explanation an integrate it into the book.

**Comment by rptaylor** [comment]
Thanks very much for the explanation @paulmillar 
> To fix this problem, the xrootd and dCache teams developed and implemented a way of signing xroot commands
Is that dcache.xrootd.security.level >=  1 and force-signing = true ?
I was also curious about that but unsure of the details;  would it be a significant security improvement and would it be likely to cause compatibility or interoperability problems? IIUC this would require use of "unix authentication" for TPC 
```
#        unix  - dCache will use "unix authentication" to authenticate.
#
#                NOTE: third-party copying between dCache instances or
#                doors requires this plugin on destination pools in
#                addition to any other auth plugins, if hash signing
#                is enforced on the pools (see
#                pool.xrootd.security.force-signing).
```
 but if unix authentication is based on a local username and does not use encryption I'm not sure how it would be useful.
 
 Is this generally the same situation as gridftp, where the control channel is encrypted but the data channel is not?
 
 Is there a way to disable xrootd TPC?

**Comment by alrossi** [comment]
Let me see if I can answer these questions without confusing you more.

Security level and force-signing have to do with signed hash verification, yes.  The highest level, 4, sends a signed hash for every request after authentication, and uses the Diffie-Hellman encryption key established during the GSI handshake to encrypt the hash.   Forced means send the hash without encryption if the protocol provides no encryption key.

In dCache, as you know, the client is always redirected from the door to a pool.  Traditionally, no additional authentication was required from the client to the pool on redirect because dCache gives the client a unique id for it to use when connecting to the file transfer (mover).  However, in order to support hash signing from the xrootd client to the pool, the former needs to be told to turn on some sort of authentication protocol.  Thus when the dCache pool is set to use hash signing (force must be true), it will tell that client to use unix.  This is a nonce ... the pool does not check the user or gid, it is just interested in subsequently enforcing the hashes.  That being said, without GSI, the hashes are unencrypted to the pool, so this is all less than optimal from the standpoint of security.

This also is independent of third-party transfers. The pool property mentioned exists to allow our TPC client to load the support of the unix protocol (and will soon be disappearing, replaced by plugin discovery); but all clients connecting to the dCache pool will be told to use unix, as stated above, in the case of security level > 0.

To summarize: without TLS, the best protection you could get would be:  GSI, security level 4, force-signing true.  Thus:

client <=> door :  GSI, encrypted signed hash
client <=> pool:   UNIX (a nonce), unencrypted signed hash

Once you upgrade to 6.2, my suggestion is to forget hash signing altogether, and instead do the following:

doors:

```
xrootd.plugins=gplazma:gsi,authz:none
xrootd.security.tls.mode=OPTIONAL
xrootd.security.tls.require-session=true
```

pools:
```
xrootd.plugins=gplazma:gsi,authz:none
xrootd.security.tls.mode=OPTIONAL
xrootd.security.tls.require-login=true
```

On the doors, the TLS session starts after the GSI handshake; on the pools, just before login.   Optional because if your xrdcp client does not support TLS, you can still do the transfer.  Should you want to prevent such clients from access, just set that property to STRICT

```
xrootd.security.tls.mode=STRICT
```

HTH,  

Al

**Comment by paulmillar** [comment]
Just to answer one of the questions you raised @rptaylor 

> Is this generally the same situation as gridftp, where the control channel is encrypted but the data channel is not?

These are somewhat similar, but the impact is quite different.

In gridftp, the control channel is fully protected, so no MitM attack is possible.  As you say, the data channel is unprotected; therefore, an attacker could modify a file's content sent over the network, thereby corrupting the data received by a transfer's destination.  This is one of the reasons why FTS always checks the data integrity after a transfer.

With the xroot protocol without request-signing or TLS, it is theoretically possible for someone to hijack a TCP session after the authentication and rename files or even delete files stored on that storage system.

One might argue over the extent to which these attack vectors are exploitable under real-world conditions: can an attacker really hijack an xroot TCP connection?

Nevertheless, GridFTP provides cryptographically strong guarantees that an attacker who hijacks the control channel cannot issue arbitrary commands (e.g., to start deleting files), which is something xroot protocol cannot guarantee without enabling request signing or TLS.

**Comment by rptaylor** [comment]
Thanks for the info.  It sounds like TLS for xroot in 6.2 is a good solution, but in the meantime we should not have exposed xrootd externally (the default port range is the LAN range which is behind ACLs but we changed xrootd to use the WAN range since ATLAS requested external access).  It makes me wonder if ATLAS considered the security issue when they requested sites to make xroot externally accessible, even going back many years to FAX, before hash signing or TLS were available to fully secure the xroot connection.

**Comment by paulmillar** [comment]
Yes, it is a bit of a surprise.

In general, I think the best we can do is try to document any caveats (as we understand them) so that people running a dCache instance are informed about the consequences of their configuration choices.  This might stimulate a discussion between a site and their users if (for example) the users are asking for something that's dangerous.

This works a little differently for WLCG because the user community is so big and geographically diverse.  So we reached out (as best we could) to try to ensure they are making decisions with the necessary information.  This has had an impact.  I believe the request signing feature (in the xroot protocol) was a result of dCache pointing out the potential problems with the earlier versions of the xroot protocol (i.e., a version without request signing).

That said, if ATLAS or CMS decide to build infrastructures (e.g., FAX/AAA, xcache, ...) then we can try to ensure that dCache fits their model, as best as possible.  However, ultimately, we have to assume that they (ATLAS/CMS/...) have understood the consequences of their decisions.

**Comment by rptaylor** [comment]
Hi Paul,
Does it make any difference if the xrootd door is writeable or not (xrootd.authz.write-paths) ?
Or once the connection is made to the pool node and the door is no longer involved, would it be possible to use the connection to write via the pool node even if the door is configured read-only?
Thanks.

**Comment by alrossi** [comment]
When you log in to the door, a mover is started.  Its IO mode is determined then, whether READ or READ-WRITE.  If you got a read-only mover from the door, you should not be able to use the UUID mapped to it to write on the pool.

If you have found that you can, we have a problem.

**Comment by paulmillar** [comment]
First, the pool's xroot-protocol endpoint is running only while it's needed (there are on-going or pending transfers).  Otherwise it shuts down.  Attempts by a client to connect will simply fail.

Second, when the client requests to read a file, the door issues the client a one-time-use bearer token (this is the UUID Al mentioned).  The client must present this token when opening the file on the pool.  Without this token, the pool will reject the open request.

Third, since the token is single-use, if the nefarious client manages to steal the token, it would need to use the token before the real client does.

Forth, the token is bound to a single transfer: a read or write operation targeting a single pool and a single file.  Even if the token was stolen and the nefarious client uses it before the real client, it could only read or write data that the genuine client has already selected.

So, there are several layers of protection against an unauthorised client transferring data.

These are not fool-proof: the pool may have ongoing transfers where a nefarious client wishes to connect, and the bearer token is currently sent over an unencrypted channel (enabling TLS in xroot would fix that).  However, it's likely that these steps are sufficient to thwart most attack vectors.

We could do more, here.  For example, we could bind the token to the client's identity (e.g., the IP address).  There's a slight risk that this might break some use-cases, so we haven't done it yet.

However, I think the biggest fix would happen outside of dCache: the community using xroot-over-TLS.  I think this is something we will likely see in the medium term, as WLCG pushes towards token-based authentication.
