### ISSUE TITLE
Feature Request: Billing Message for msgType:store to show URI in status fields

### ISSUE THREAD

**Issue by christianvoss** [dCache/dcache#6007]
Dear dCache developers,

in light of a recent incident with empty URIs reported by our HSM script we thought about making the reported URI available in the Kafka billing stream.

Our idea is based on the changes to the remove messages, where a successful remove (status code 0) contains as status message the reason why the file was removed. Before that the status message field was simply empty. Could something similar be done for store messages. As of now, the status message for status code 0 is empty.

We have something like this in mind:
```
{
    "billingPath": "/",
   ... 
   "msgType": "store",
   ...
    "status": {
        "code": 0,
        "msg": " dcache://dcache/?store= ..."
    },
   ...
    "transferTime": 359811,
    "version": "1.0"
}
```
Overall, this would allow us to monitor and react to empty URI very easily, currently we have changed the Log-Level on all our flush pools to info, to monitor, alarm and archive the reported URIs.

Thanks a lot,
Christian for the DESY-HH dCache operations team

**Comment by paulmillar** [comment]
Hi Christian,

I think this is a good idea, and shouldn't be too difficult to do.

I've a couple of thoughts / questions.

1. I know we used the `status.msg` field for the deletion messages, but would it make sense to include the storage URI in the Kafka message as its own field?  I'm wondering whether adding a `location` (or `storage-url`, or ...) field might provide a "better" (more semantically precise) way of presenting this information.  What are your thoughts?
2. If you have an idea what makes a "good" and "bad" storage URI, perhaps we could teach this distinction to dCache?  An empty URI is an obvious thing to check, but perhaps we could add a regular expression that the URI must match before dCache accepts the URI as valid.  This would be independent of adding the URI to the Kafka message.

Cheers,
Paul.

**Comment by christianvoss** [comment]
Hi Paul,

concerning your first point, I'd leave that up to you, the `storage-uri` would be are more 'correct' place rather than hijacking the status message. It would be empty in case of a failed store, or would you leave it out in case the store failed? The latter case would make data analyses or monitoring a bit more tedious I think. Storing it in the message would make monitoring conditions maybe a bit more straight forward? From our point of view, both solutions would be fine, personally, I think having the URI in an own filed would be the 'correct' solution I guess, but please leave the key also in messages where there is a failed store.

Concerning the second points, I think it's difficult for you? An empty URI for example is valid within certain flush workflows, hence us not observing it in the first place. I'm not sure how many different formats the different HSM backend  have. One could argue, that this is part of each sites flush scripts since they know what their backend need? Or do you think about using a e.g. a pool property for us to ingest a regular expression to check against? In doing that each site could provide its own 'correct' URI RegEx.

Thanks a lot for you quick reply,
Christian

**Comment by paulmillar** [comment]
Hi Christian,

Here's a concrete proposal:

For successful flushes, the pool-sent Kafka JSON would contain the URI returned by the script in the `location` field.  If the flush fails then the JSON would not include any `location` field.

For stage requests and tape-delete requests, we add the `location` field.  This field would be present for both successful and failed operations.

All other notifications (e.g., pool's file upload, doors' transfer notifications) are unchanged.

For the regexp idea: the value would need to be site-specific (perhaps instance-specific); therefore, this would need to be a configuration property (or, perhaps, something in the pool setup file).   The default regexp would allow any URI (for backwards compatibility), but an admin could configure this to be something more restrictive.

If the URI does not match then the flush request is paused and manual intervention (from the admin) would be required to "try again".  I think auto-retrying would be bad, because of the risk that a file is written to tape many, many times.

In theory, this extra feature in dCache isn't necessary.  This is because the same check could be placed in the script; however, the property could provide an extra insurance for admins.

Such a regexp could provide better protection that just checking whether the URI is non-empty; for example, if a valid URI has different fields (as query parameters; for example) then the regexp could check that all the fields are present and contain valid values.  Regexp is not perfect -- there are URI schema that might be hard to validate with a regexp pattern; however, I think it could be a reasonable compromise.

Cheers,
Paul.

**Comment by christianvoss** [comment]
Hi Paul,

thanks for the quick ideas! I like the location field for the billing message. For restores/tape deletes it might be useful as well, true. Failed restores due to some strange/empty URI would be easy to spot. Again, I'd prefer the field to be there for any flush since this makes data analysis a lot easier and less error prone. But in the end it's another try, except I've to apply to the dCache billing logs. But, we agreed to disagree there ;) I remember something about the war :P

But thanks a lot for considering adding the option!

Concerning the URI check, I agree, having another check-layer is good to have. And to require manual intervention if the URI doesn't match the pattern is a good idea as well. This could help all sites with any HSM backend to keep locations consistent with the specifications no matter the HSM.

I guess you have a property in mind, that would be pass through as default?

I think both proposal would be nice to have and make monitoring and checks easier and more straight forward to do.

Thanks a lot!
Christian

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/13141/
Patch: https://rb.dcache.org/r/13130/
