### ISSUE TITLE
Limiting matches via gPlazma multi-map plugin?

### ISSUE THREAD

**Issue by sfayer** [dCache/dcache#6472]
Hi,

I have another OIDC related question from my recent testing... In my multi-map file I have:
```
oidcgrp:/cms/production username:cmsprd
oidcgrp:/cms username:cmsusr
```

I'm using the WLCG tokens from the CMS endpoint. By default my wlcg.groups field contains just the base `/cms` group, this works correctly and maps me to the cmsusr account.

I also have access to the optional production group, if I request that then my token then contains a wlcg.groups claim with two entries, the more specific one first:
```
[
  /cms/production,
  /cms
]
```

I was expecting that either the ordering in the token would take precedence or the ordering in the map file (It didn't really matter either way), but instead my request gets rejected with the fairly obvious error in my gPlazma log:
```
authzdb REQUISITE:FAIL (multiple usernames) => FAIL (ends the phase)
```

Is there a way where I can get just the production mapping to take precedence over the base one rather than ending up with both? (i.e. is there a way to say "if this line matches, stop mapping here" in the multi-map file?)
Is there a better way to achieve this kind of mapping? (I'm only trying things out, so perhaps this isn't the way I should be doing this at all?).

Regards,
Simon

**Comment by paulmillar** [comment]
Yes, this is a "known problem" with multimap and how it handles "unique" principals.  A login must have exactly one username, exactly one uid, and exactly one primary gid.

Although the `wlcg.groups` claim contains groups, there's no priority.  One group must be first in the list (because that's how JSON works), but there's no special significance given to this group.  This is different from VOMS, where the FQANs are ordered and, in particular, the first FQAN is the primary FQAN.

Therefore the priorities must come from dCache, not from the token.

Providing this priority is (currently) not possible with a single multiple file.  If you have multiple group accounts then you end up with multiple usernames and the login fails.  This is exactly the problem you described.

However, it _is_ possible with multiple multimap files.  I'll describe this a bit further on.

As it happens, I've been thinking how best to support multiple group accounts with a single multimap file.  I have some ideas, and hope to have something "soon", but I'm not sure exactly when this will be.

As it happens, I replied to someone else on exactly this topic.  I really need to update the gPlazma documentation!

In the meantime, here's a copy from my reply.  I hope this provides enough information to see how you can solve your problem.

---

One problem currently with multimap is with how to describe which of several values of a unique principal (like username or uid) should be used.

For example, VOMS guarantees that if it asserts membership of FQAN `/atlas/Role=lcgadmin` then it will always assert FQAN `/atlas`.

From your configuration, you want clients with FQAN `/atlas/Role=lcgadmin` to have username `sgmatl01` and those FQAN `/atlas` to have `atlas001`, but a client with `/atlas/Role=lcgadmin` will always also have FQAN `/atlas`, so dCache has to (somehow) know which username to use: `sgmatl01` or `atlas001` ?

It is possible to handle this with multimap, but it's currently a bit awkward.

To do it, you need to have multiple multimap files: one for each "priority level".  These multimap files are included in `gplazma.conf` with "sufficient".  This way, if there's a match, in one priority level the subsequent priority levels are not consulted.

So, just for illustrative purposes, lets say a client is never asserts both FQAN `/atlas/Role=lcgadmin` and FQAN `/atlas/Role=production`.  We can support your configuration by having the two multimap files.

The first file (called 'multimap-special.conf', say) is:


    "dn:/C=DE/O=GermanGrid/OU=LMU/CN=Rodney Walker" username:prdatl01 uid:50201 gid:1307,true
    fqan:/atlas/Role=lcgadmin        username:sgmatl01 uid:60201 gid:1309,true
    fqan:/atlas/Role=production      username:prdatl01 uid:50201 gid:1307,true


The second multimap file (called `multimap-fallback.conf`, say) provides the "fall-back" account for all ATLAS users not described above.  Here's the contents of `multimap-fallback.conf`:


    fqan:/atlas  username:atlas001 uid:10761 gid:1307,true


These two multimap files are included in `gplazma.conf` like this:


    map  sufficient  multimap gplazma.multimap.file=/etc/dcache/multimap-special.conf
    map  sufficient  multimap gplazma.multimap.file=/etc/dcache/multimap-fallback.conf


That should work, but you're forced to repeat the uid/gid on each line.

You can improve this by "factoring out" the mapping from username to uid/gid into a separate multimap file, with something like the following.

multimap-id-to-username-1.conf


    "dn:/C=DE/O=GermanGrid/OU=LMU/CN=Rodney Walker" username:prdatl01
    fqan:/atlas/Role=lcgadmin        username:sgmatl01
    fqan:/atlas/Role=production      username:prdatl01


multimap-id-to-username-2.conf


    fqan:/atlas  username:atlas001


multimap-username-to-uid+gid.conf


    username:prdatl01  uid:50201 gid:1307,true
    username:sgmatl01  uid:60201 gid:1309,true
    username:atlas001  uid:10761 gid:1307,true


The mapping part of the `gplazma.conf` file now looks like:


    map  optional    multimap gplazma.multimap.file=/etc/dcache/multimap-id-to-username-1.conf
    map  sufficient  multimap gplazma.multimap.file=/etc/dcache/multimap-username-to-uid+gid.
    map  optional    multimap gplazma.multimap.file=/etc/dcache/multimap-id-to-username-2.conf
    map  sufficient  multimap gplazma.multimap.file=/etc/dcache/multimap-username-to-uid+gid.conf


The `multimap-username-to-uid+gid.conf` file is used both to hold the uid/gid information and to provide a test, checking whether the mapping has succeeded.

This will work and (I think) is better than the earlier version, it's still not great.

**Comment by sfayer** [comment]
Thanks Paul,

Yes, we were able to get this working by using multiple instances of the multimap file plugin.

Regards,
Simon
