### ISSUE TITLE
Invalid config event received

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#6503]
Hey.

On 7.2.10, these show up on nearly every domain startup:
```
Feb 22 20:25:55 lcg-lrz-dcache0 dcache@filesystem[139531]: 2022-02-22 20:25:55+01:00 (System) [] Invalid config event received: {server.2=lcg-lrz-dcache1.grid.lrz.de:2182:2183:participant, server.1=lcg-lrz-dcache0.grid.lrz.de:2182:2183:participant, server.3=lcg-lrz-dcache2.grid.lrz.de:2182:2183:participant, version=0}
Feb 22 20:25:55 lcg-lrz-dcache0 dcache@filesystem[139531]: 2022-02-22 20:25:55+01:00 (System) [] Invalid config event received: {server.2=lcg-lrz-dcache1.grid.lrz.de:2182:2183:participant, server.1=lcg-lrz-dcache0.grid.lrz.de:2182:2183:participant, server.3=lcg-lrz-dcache2.grid.lrz.de:2182:2183:participant, version=0}
```

Any ideas?

Cheers,
Chris.

**Comment by lemora** [comment]
Hi Chris.

Since version 6.2 dCache requires the associated ZooKeeper servers to be of version 3.5 or above, where the ZooKeeper configuration format has changed: https://zookeeper.apache.org/doc/r3.5.3-beta/zookeeperReconfig.html#ch_reconfig_format

In order for the logged messages to go away, you would need to remove the `clientPort=...` line and add the respective port to the end of each server line after a semicolon. The lines would then look something like this:
```
server.1=zookeeper-node01:2888:3888;2181
server.2=zookeeper-node02:2888:3888;2181
```

Lea

**Comment by calestyo** [comment]
Hey Lea.

Thanks, that fixed the issue.

Could you please add that to the release notes of all the dCache versions >=6.2? And with add I mean in the **next** minor-release entry therein,... not in some older or the general section, which no one will read again, after that had been done already.

Most sites will typically just run ZK **because** of dCache and not as a native standalone service. So such things would be quite helpful to have in the release notes (i.e. things where admins really need to change something) – much more than single bug fixes or performance improvements, which anyone who wants to know about them, will find in detail in the git log :-)

I guess from my side, we can close that issue... except you want to keep it for tracking that this goes into the release notes?

Thanks,
Chris.
