### ISSUE TITLE
Webdav: File upload without Content-Length doesn't give error

### ISSUE THREAD

**Issue by ZNikke** [dCache/dcache#6601]
When investigating whether dCache supports some variant of "streaming" uploads, ie uploads without known length at start of upload, I noticed that this variant without Content-Length header (which probably is out-of-spec) doesn't seem to be supported but dCache returns success on the upload:

```
curl -D- -L -T testfile -E /tmp/x509up_u${UID} -H "Content-Length:" https://host/path/sfile
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Date: Wed, 20 Apr 2022 14:31:16 GMT
Server: dCache/7.2.13
Accept-Ranges: bytes
ETag: "00002981E9CE5880404680D7A730C3DD11DC_1197634663"
Transfer-Encoding: chunked

curl: (55) SSL_write() returned SYSCALL, errno = 32
```

I would have expected either a successful upload or an immediate error code, the current result is a 0-byte file being created...

This is with dCache 7.2.13.

(Side note: chunked upload seems to work as expected to upload a file of unknown size).

**Comment by kofemann** [comment]
Hi @ZNikke ,

I would expect that have logged why transfer have failed. Can you add that error message to this issue?
Thanks.

**Comment by paulmillar** [comment]
At the risk of pointing out the obvious, here are some observations.

First, the response `HTTP/1.1 100 Continue` means the door did not redirect the client to the pool.  Instead, the door proxied the file's data, receiving the data (in chunks) and relaying it to the pool.

Second, the curl option `-H "Content-Length:"` tells curl to suppress the `Content-Length` header.  This _forces_ curl to use chunked upload.  This is reflected in the response header `Transfer-Encoding: chunked`.

Finally, the `errno = 32` is EPIPE, which indicates the remote end (i.e., dCache) closed the connection when the client wanted to send something.  Since this happened after the (apparently) successful upload, I imagine this is the TLS "close notify" alert.  The "close notify" alert is always sent by the TLS client, as the final message.  For some reason, dCache appears to be tearing down the TCP connection before receiving this alert, which is (in itself) rather odd.

It could be that the EPIPE error is a further symptom of some common problem.

As @kofemann says, further information would be helpful.

**Comment by ZNikke** [comment]
After having slept on it, yeah it's a botched attempt on my part to recreate what a weird (non-standard) client was trying to do.

As proper chunked upload works, let's just close this as me being confused and wasting your time ;-)

**Comment by paulmillar** [comment]
@znikke To be honest, I think you've found a legitimate bug.

There's absolutely no way that dCache should report success to the client, but only have a zero-length file.

It doesn't matter what the client does: dCache should only report success if it has all the data.  If the client does something "crazy" then dCache should report some kind of `4xx` status code.

I consider this issue still open, and something that needs to be fixed.
