### ISSUE TITLE
dcache-view: not taking values from oidc token after upgrad to 8.2

### ISSUE THREAD

**Issue by elenamplanas** [dCache/dcache#6928]
After upgrading to 8.2 our test environment, when we try to login using OIDC, no values are passed to gplazma to login and map the user.

The previous version of dCache was 7.2, and we've not changed anything.Witthe same configuration login is successful in version 7.2, but in 8.2 the message shown is "user is undefined".

On gplazma i could see that info:
```
LOGIN FAIL
 |    in: Origin[172.16.111.4]
 |        BearerTokenCredential[eyJh+{Hash=MakgMXgqVTI}+TEuw]
 |
 +--AUTH OK
 |   |
 |   +--htpasswd OPTIONAL:FAIL (no username and password) => OK
 |   |
 |   +--x509 OPTIONAL:FAIL (no X.509 certificate chain) => OK
 |   |
 |   +--voms OPTIONAL:FAIL (no X509 certificate chain) => OK
 |   |
 |   +--jaas OPTIONAL:FAIL (no login name) => OK
 |   |
 |   +--oidc OPTIONAL:FAIL (intended for account) => OK
 |   |
 |   +--scitoken OPTIONAL:FAIL (intended for [account]) => OK
 |
 +--MAP FAIL
 |   |
 |   +--vorolemap OPTIONAL:FAIL (no record) => OK
 |   |
 |   +--gridmap OPTIONAL:FAIL (no mapping) => OK
 |   |
 |   +--authzdb SUFFICIENT:FAIL (no mappable principal) => OK
 |   |
 |   +--mutator OPTIONAL:OK => OK
 |   |
 |   +--multimap OPTIONAL:FAIL (no mappable principals) => OK
 |   |
 |   +--multimap OPTIONAL:FAIL (no mappable principals) => OK
 |   |
 |   +--multimap SUFFICIENT:FAIL (no mappable principals) => OK
 |   |
 |   +--multimap SUFFICIENT:FAIL (no mappable principals) => OK
 |   |
 |   +--nsswitch REQUISITE:FAIL (no mapping) => FAIL (ends the phase)
 |
 +--(ACCOUNT) skipped
 |
 +--(SESSION) skipped
 |
 +--(VALIDATION) skipped
```

Has anything change in this version?
Thanks!

**Comment by paulmillar** [comment]
According to the failure report (scitoken says `intended for [account]` and oidc says `intended for account`), the token is being rejected because of the audience (`aud`) claim.  The audience claim describes for which service the token is intended.  Seemingly, this token is intended to be used on a service called "account", and no other service.  Your dCache instance doesn't believe it is that service, so it is rejecting the token.

If you believe dCache _should_ accept tokens intended for the "account" service (and no other service) then update the `gplazma.oidc.audience-targets` and `gplazma.scitoken.audience-targets` configuration properties, as appropriate.

If you believe dCache _should not_ accept tokens intended for the "account" service (and no other service) then dCache is correctly rejecting the token.  You should update your procedure for obtaining tokens so that they contain the correct audience claim.

Unlike the scitoken plugin, the oidc plugin didn't used to check the audience claim (this is for "reasons").  Support for checking the audience claim (in the oidc plugin) was added with dCache v8.0.  The change wasn't backported because it could break existing deployments.  If you're upgrading from 7.2 to 8.2 then this could explain why the token started to fail.

**Comment by elenamplanas** [comment]
Thanks for the explanation!

We're going to review our needs, and configure the parameter if needed.
