### ISSUE TITLE
PSQLException with Webdav OPTIONS request

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#7112]
Hi,

I upgraded from 8.2.12 to 8.2.18 yesterday and users started to see 500 Server Error during HTTP OPTIONS request : 

```
 curl -i -L --capath /etc/grid-security/certificates --cacert /tmp/x509up_u41386 --cert /tmp/x509up_u41386 --output /dev/stdout -X OPTIONS https://ccdavrubinint.in2p3.fr:2880/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 500 Server Error
Date: Wed, 05 Apr 2023 06:51:49 GMT
Server: dCache/8.2.18
Content-Type: text/plain;charset=utf-8
Content-Length: 652

Internal problem: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [SELECT * FROM resolve_path(?, ?)]; ERROR: upper bound of FOR loop cannot be null;  Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable;PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN; nested exception is org.postgresql.util.PSQLException: ERROR: upper bound of FOR loop cannot be null;  Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable;PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN
```

On PnfsManager : 

```
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]: 05 Apr 2023 08:51:49 (PnfsManager2) [door:webdav-ccdcacli449@webdav-ccdcacli449Domain:AAX4kTnxl9A webdav-ccdcacli449 PnfsGetFileAttributes] Error while retrieving file attributes: PreparedStatementCallback; SQL [SELECT * FROM resolve_path(?, ?)]; ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN; nested exception is org.postgresql.util.PSQLException: ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [SELECT * FROM resolve_path(?, ?)]; ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN; nested exception is org.postgresql.util.PSQLException: ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.dcache.chimera.PgSQL95FsSqlDriver.resolvePath(PgSQL95FsSqlDriver.java:275)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.dcache.chimera.JdbcFs.resolvePath(JdbcFs.java:1578)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at jdk.internal.reflect.GeneratedMethodAccessor281.invoke(Unknown Source)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.dcache.commons.stats.MonitoringProxy.invoke(MonitoringProxy.java:52)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at com.sun.proxy.$Proxy28.resolvePath(Unknown Source)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.dcache.chimera.namespace.ChimeraNameSpaceProvider.resolveSymlinks(ChimeraNameSpaceProvider.java:1939)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.ForwardingNameSpaceProvider.resolveSymlinks(ForwardingNameSpaceProvider.java:225)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.resolveSymlinks(PnfsManagerV3.java:3344)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.checkRestriction(PnfsManagerV3.java:3297)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.checkRestriction(PnfsManagerV3.java:3268)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.getFileAttributes(PnfsManagerV3.java:2843)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally_aroundBody4(PnfsManagerV3.java:2664)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.PnfsManagerV3$AjcClosure5.run(PnfsManagerV3.java:1)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:67)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:73)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:71)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally(PnfsManagerV3.java:2635)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.processPnfsMessage(PnfsManagerV3.java:2606)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at diskCacheV111.namespace.PnfsManagerV3$ProcessThread.run(PnfsManagerV3.java:2313)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at java.base/java.lang.Thread.run(Thread.java:829)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]: Caused by: org.postgresql.util.PSQLException: ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:678)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
Apr 05 08:51:49 ccdcamcli21 dcache@pnfsDomain2[2691902]:         ... 27 common frames omitted

```

I tried to run dcache database update but no changes.

Cheers,
Adrien

**Comment by alrossi** [comment]
Fixed with next release.

https://github.com/dCache/dcache/pull/7092#event-8921853678
[https://opengraph.githubassets.com/87787c9ba5af34eeeb2b4dd2c6bf1052b158e059382cd7df78f6eea71ac1460b/dCache/dcache/pull/7092]<https://github.com/dCache/dcache/pull/7092#event-8921853678>
chimera: fix bug in resolve_path stored procedure by alrossi · Pull Request #7092 · dCache/dcache<https://github.com/dCache/dcache/pull/7092#event-8921853678>
Motivation: https://rb.dcache.org/r/13908/ ***@***.*** introduced symlink resolution into the namespace restriction checks. The base code for this was a new st...
github.com


Cheers, Al


________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
WH 566
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________
From: ageorget ***@***.***>
Sent: Wednesday, April 5, 2023 1:57 AM
To: dCache/dcache ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dCache/dcache] PSQLException with Webdav OPTIONS request (Issue #7112)


Hi,

I upgraded from 8.2.12 to 8.2.18 yesterday and users started to see 500 Server Error during HTTP OPTIONS request :

 curl -i -L --capath /etc/grid-security/certificates --cacert /tmp/x509up_u41386 --cert /tmp/x509up_u41386 --output /dev/stdout -X OPTIONS https://ccdavrubinint.in2p3.fr:2880/<https://urldefense.proofpoint.com/v2/url?u=https-3A__ccdavrubinint.in2p3.fr-3A2880_&d=DwQCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=60rQ0HHqHmEY1P6VSdyuTQ&m=ttmfDz3hJY4X9Qr6vw2TheZY70js5Rs17YPFwvqgjbcmvEz5nKIYByW0f85THVMy&s=uTFQR4-0q8bvR9pR7pwFfm8KJ_jpairMcANLUXwRZoQ&e=>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 500 Server Error
Date: Wed, 05 Apr 2023 06:51:49 GMT
Server: dCache/8.2.18
Content-Type: text/plain;charset=utf-8
Content-Length: 652

Internal problem: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [SELECT * FROM resolve_path(?, ?)]; ERROR: upper bound of FOR loop cannot be null;  Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable;PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN; nested exception is org.postgresql.util.PSQLException: ERROR: upper bound of FOR loop cannot be null;  Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable;PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN


On PnfsManager :

Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]: 05 Apr 2023 08:51:49 (PnfsManager2) ***@***.***:AAX4kTnxl9A webdav-ccdcacli449 PnfsGetFileAttributes] Error while retrieving file attributes: PreparedStatementCallback; SQL [SELECT * FROM resolve_path(?, ?)]; ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN; nested exception is org.postgresql.util.PSQLException: ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [SELECT * FROM resolve_path(?, ?)]; ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN; nested exception is org.postgresql.util.PSQLException: ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.dcache.chimera.PgSQL95FsSqlDriver.resolvePath(PgSQL95FsSqlDriver.java:275)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.dcache.chimera.JdbcFs.resolvePath(JdbcFs.java:1578)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at jdk.internal.reflect.GeneratedMethodAccessor281.invoke(Unknown Source)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.dcache.commons.stats.MonitoringProxy.invoke(MonitoringProxy.java:52)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at com.sun.proxy.$Proxy28.resolvePath(Unknown Source)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.dcache.chimera.namespace.ChimeraNameSpaceProvider.resolveSymlinks(ChimeraNameSpaceProvider.java:1939)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.ForwardingNameSpaceProvider.resolveSymlinks(ForwardingNameSpaceProvider.java:225)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.resolveSymlinks(PnfsManagerV3.java:3344)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.checkRestriction(PnfsManagerV3.java:3297)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.checkRestriction(PnfsManagerV3.java:3268)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.getFileAttributes(PnfsManagerV3.java:2843)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally_aroundBody4(PnfsManagerV3.java:2664)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.PnfsManagerV3$AjcClosure5.run(PnfsManagerV3.java:1)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:67)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:73)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:71)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally(PnfsManagerV3.java:2635)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.PnfsManagerV3.processPnfsMessage(PnfsManagerV3.java:2606)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at diskCacheV111.namespace.PnfsManagerV3$ProcessThread.run(PnfsManagerV3.java:2313)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at java.base/java.lang.Thread.run(Thread.java:829)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]: Caused by: org.postgresql.util.PSQLException: ERROR: upper bound of FOR loop cannot be null
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:   Where: PL/pgSQL function path2inumber(bigint,character varying) line 9 at FOR with integer loop variable
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]: PL/pgSQL function resolve_path(bigint,character varying) line 6 at RETURN
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:678)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
Apr 05 08:51:49 ccdcamcli21 ***@***.***[2691902]:         ... 27 common frames omitted



I tried to run dcache database update but no changes.

Cheers,
Adrien

**Comment by alrossi** [comment]
Actually, it's in 8.2.19

https://www.dcache.org/old/downloads/1.9/release-notes-8.2.shtml


________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
WH 566
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by ageorget** [comment]
Perfect, thanks for the fix!

Cheers,
Adrien
