### ISSUE TITLE
gPlazma incompatibiliti detween  version  before and after 8.2.13

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#7279]
Due to missing `serialVersionUID` the modifications to MultiTargetedRestriction in commit https://github.com/dcache/dcache/commit/0d8931c49f8a2e911f02526dec40cf9dee062ca2 broke compatibility:

```
dmg.cells.nucleus.SerializationException: Failed to deserialize object:
    java.io.InvalidClassException: org.dcache.auth.attributes.MultiTargetedRestriction;
         local class incompatible: stream class desc serialVersionUID = -4604505680192926544,
         local class serialVersionUID = 4018230211437837262
```

**Comment by alrossi** [comment]
How do you suggest we handle this?

**Comment by kofemann** [comment]
All serializable classes (everything sent between cells) must contain pre-calculated serialVersionUID.

**Comment by alrossi** [comment]
Yes, I understand that.   There is a serialVerionUID in the Authorization inner class (= -1).  

Should we change that to a generated one?  Will fixing this after the fact like this solve the problem ?

**Comment by kofemann** [comment]
The inner class is fine, as it has a `fixed` serialVerionUID. The MultiTargetedRestriction itself doesn't have.

**Comment by alrossi** [comment]
Interesting oversight.  Prefix and Composite restrictions both have a generated id.   OK, patch coming up

**Comment by paulmillar** [comment]
At the risk of saying what people already know ...

As I understand it, the impact of this problem is that it breaks backwards compatibility.  We say that sites can make bug-fix upgrades on any individual dCache node in the dCache cluster.  Because of this issue, this promise is no longer true.

Anyone making a bug-fix release (on the supported branch, like 8.2) is forced to upgrade all dCache non-pool nodes in one go.  I'm not sure whether the Restriction are sent to the pool (could be).  If so, then the issue forces dCache admins to upgrade all dCache nodes.

Setting the `serialVerionUID` value to `-1` would result in forcing all dCache sites (those already affected and those not yet affected) to do a simultaneous upgrade.  For those already affected, this would be the second such whole-instance upgrade.

Setting the  `serialVerionUID` value to the calculated value *before* the change would force sites that have already suffered from the problem to go through a whole-instance upgrade again.

Setting the `serialVerionUID` value to the calculated value *after* the change would force sites that have not yet suffered from the problem to go through a whole-instance upgrade.

The best choice probably depends on the number of sites already affected.

The release notes should also be updated.

**Comment by alrossi** [comment]
Thanks for the clarification.  I figured this was an intricate issue.   So the patch currently does the last, but perhaps the second choice is the best?

**Comment by kofemann** [comment]
Let `fix` the current state., e.g. use the after change value.

**Comment by alrossi** [comment]
OK.
