### ISSUE TITLE
TPC Copy error 507 UNKNOWN_RESPONSE_CODE

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#7445]
Hi,

For the last 24h, CMS TPC COPY transfers are failing from our site to cmseos.fnal.gov with the error `507 UNKNOWN_RESPONSE_CODE`
According to the HTTP status code, this is related to insufficient storage (from RFC 4918)

From the webdav door logs : 
`level=WARN ts=2023-12-01T13:55:31.262+0100 event=org.dcache.webdav.request request.method=COPY request.url=https://ccdcatli345.in2p3.fr:2880/disk/data/store/temp/user/bolinl.fcc3e2155506f00db7be0490e76782af913b8167/lpcbphy/noreplica/2022and20234mNtuple/HI/HIRUN3miniAOD_data/HIPhysicsRawPrime20/RUN3Data_2023prime20v2_mini/231130_145407/0006/mymultilep_6921.root response.code=202 socket.remote=[2001:1458:301:cd::100:30e]:49508 user-agent="libdavix/0.8.4 libcurl/7.69.0-DEV" user.dn="CN=1701355296,CN=1160758833,CN=3023606134,CN=238683721,CN=895609486,CN=1824199756,CN=Bolin Li,CN=843145,CN=bolinl,OU=Users,OU=Organic Units,DC=cern,DC=ch" user.mapped=3033:119[b85j9qM9:IXKzfIQr] tpc.credential=none tpc.error="rejected PUT: 507 UNKNOWN_RESPONSE_CODE" tpc.require-checksum=false tpc.destination=https://cmseos.fnal.gov:9000/eos/uscms/store/group/lpcbphy/noreplica/2022and20234mNtuple/HI/HIRUN3miniAOD_data/HIPhysicsRawPrime20/RUN3Data_2023prime20v2_mini/231130_145407/0006/mymultilep_6921.root duration=627`

On pools : 
`Dec 01 14:00:02 ccdcacli373.in2p3.fr dcache@ccdcacli373-pool-cms-analysis-li373a-Domain[14424]: 01 Dec 2023 14:00:02 (pool-cms-analysis-li373a) [door:webdav-ccdcatli345@webdav-ccdcatli345Domain:AAYLclitx2k RemoteTransferManager PoolDeliverFile 0000450BF6F01DC24CF89726B8912B5C24BB] Transfer failed: rejected PUT: 507 UNKNOWN_RESPONSE_CODE`

This error message should be  "INSUFFICIENT_STORAGE" instead of UNKNOWN_RESPONSE_CODE.

**Comment by paulmillar** [comment]
The problem here comes from an unsuccessful HTTP-TPC PUSH request, with the data stored at IN2P3.  In other words, the dCache pool `pool-cms-analysis-li373a` is undertaking an HTTP `PUT` request, targeting the `https://cmseos.fnal.gov:9000/` endpoint.  dCache is reporting that this PUT request has failed.

The pool is reporting the underlying problem as `rejected PUT: 507 UNKNOWN_RESPONSE_CODE`.  This error message contains both the HTTP verb that failed (`PUT`) and the HTTP status line from the remote server (`507 UNKNOWN_RESPONSE_CODE`).  The HTTP status line itself it make up of the HTTP status code (`507`) and the HTTP reason phrase (`UNKNOWN_RESPONSE_CODE`).

So, the `UNKNOWN_RESPONSE_CODE` message you describe here actually comes from the remote endpoint (`https://cmseos.fnal.gov:9000/`) and not IN2P3's dCache.  (I double-checked the dCache, Milton and Jetty source code: none of them have this phrase.)

The default reason phrase for 507 is "insufficient storage" (or some variation thereof), however, there is no requirement for the reason phrase to be exactly these words.  Although `UNKNOWN_RESPONSE_CODE` is an unusual choice of reason phrase, it is not wrong per se.  However, it's highly likely that this message isn't what the developers had in mind, so please feel free to open a GGUS ticket against the admins of `cmseos.fnal.gov` and/or a support issue against EOS.
