### ISSUE TITLE
HTTP-TPC doesn’t support percent-encoded paths

### ISSUE THREAD

**Issue by SarwarAleem** [dCache/dcache#7512]
The Source or Destination URL may contains characters that are percent encoded (sometimes this is required). Currently, dCache support for HTTP-TPC does not decode any percent-encoded characters in the Source/Destination URL, resulting in transfers failing.

**Comment by DmitryLitvintsev** [comment]
Just a word of warning. By allowing spaces in file names we are "daring" underlying HSM storage not to choke on them too. So I would like to gauge how important this support for dCache.

**Comment by paulmillar** [comment]
Realistically, fixing this problem is probably not urgent and will probably end up with me fixing the problem (when I get a spare moment) anyway.  I wanted this issue mostly to make sure it isn't forgotten.

Specifically on your warning, I believe dCache supports spaces in filenames with other protocols (not 100% sure about xroot, but pretty sure about everything else), so I don't see why dCache shouldn't support spaces with HTTP-TPC.

The tape issue is, perhaps, a concern.  WLCG doesn't have files with spaces in it (otherwise we would have noticed this problem earlier), so our major tape users shouldn't have a problem.

As an aside, if you want to see the kind of things dCache supports as filenames, take a look at the [UTF-8 test on prometheus](http://prometheus.desy.de/UTF-8/).  Yes, dCache's namespace works fine with filenames written in Viking runes.  I don't know if anyone has tried writing such files to tape, though.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/14239/
