### ISSUE TITLE
When pool with restore goes down, it triggers a second restore request

### ISSUE THREAD

**Issue by lemora** [dCache/dcache#7586]
Once the pool comes up again, even if there is already a staged copy on disk, the original restore resumes.
Additionally, when trying to access the disk copy, PoolManager refuses to serve it because it sees that a restore is ongoing and assumes that there is no replica on disk.

The second issue probably need to be fixed in
https://github.com/dCache/dcache/blob/052d56b970cadbba2ac3e212870eaf50cb13883b/modules/dcache/src/main/java/diskCacheV111/poolManager/RequestContainerV5.java#L833

**Comment by DmitryLitvintsev** [comment]
What does it mean "pool with restore"? Does this mean a pool that has restore in queue? If it goes down all restores are gone and no replica of that file there. The issue, I thought, was with just a pool going down with all the replicas on it unavailable. Users try to access the files, they trigger stage. Meanwhile pool comes back up, but none of the files being staged can be read because there are staging requests in PM (Issue #7587)

**Comment by lemora** [comment]
Well, the phrasing is perhaps a bit convoluted. We also have the issue that we are not able to cancel ongoing restores on the tape side, but that might be hard to address.

Nobody had opened the agreed-upon issue when I checked yesterday, so I created this one. The second part (with the reference to `RequestContainerV5`) is now redundant to https://github.com/dCache/dcache/issues/7587, of course.

I'll close this issue and we can follow-up in the other one.
